{
 "title": "Grafana Dashboard for Veeam Enterprise Manager",
 "description": "Grafana Dashboard for Veeam Enterprise Manager RESTful API. Grafana 7",
 "tags": [
  "Veeam",
  "Enterprise Manager"
 ],
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "enterprisemanager",
    "label": "Enterprise Manager",
    "query": "SHOW TAG VALUES FROM veeam_em_overview WITH KEY=host"
   },
   {
    "name": "veeamserver",
    "label": "Veeam Backup Server",
    "query": "SHOW TAG VALUES FROM veeam_em_job_sessions WITH KEY=veeamVBR"
   },
   {
    "name": "repository",
    "label": "Backup Repository",
    "query": "select DISTINCT(\"veeamRepositoryName\") from (select \"veeamRepositoryCapacity\",\"veeamRepositoryName\" from \"veeam_em_overview_repositories\" WHERE $timeFilter AND \"veeamVBR\" =~ /$veeamserver/)"
   },
   {
    "name": "backupjob",
    "label": "Backup Job",
    "query": "select DISTINCT(\"veeamBackupSessionsName\") from (select \"veeamBackupSessionsJobResult\",\"veeamBackupSessionsName\" from \"veeam_em_job_sessions\" WHERE $timeFilter AND \"veeamVBR\" =~ /$veeamserver/)"
   },
   {
    "name": "replicajob",
    "label": "Replica Job",
    "query": "select DISTINCT(\"veeamReplicaSessionsName\") from (select \"veeamReplicaSessionsDuration\",\"veeamReplicaSessionsName\" from \"veeam_em_job_sessions\" WHERE $timeFilter AND \"veeamVBR\" =~ /$veeamserver/)"
   },
   {
    "name": "backupvm",
    "label": "Protected VM",
    "query": "select DISTINCT(\"veeamBackupSessionsVmDisplayName\") from (select \"veeamBackupSessionsJobVMResult\",\"veeamBackupSessionsVmDisplayName\" from \"veeam_em_job_sessionsvm\" WHERE $timeFilter AND \"veeamVBR\" =~ /$veeamserver/)"
   },
   {
    "name": "replicavm",
    "label": "Replicated VM",
    "query": "select DISTINCT(\"veeamReplicaSessionsJobVMResult\") from (select \"veeamBackupSessionsJobVMResult\",\"veeamReplicaSessionsVmDisplayName \" from \"veeam_em_job_sessionsvm\" WHERE $timeFilter AND \"veeamVBR\" =~ /$veeamserver/)\n\n"
   },
   {
    "name": "veeamversion",
    "query": "select last(\"veeamBackupServersVersion\") from (select \"veeamBackupServersPort\",\"veeamBackupServersVersion\" from \"veeam_em_backup_servers\" WHERE $timeFilter AND \"veeamVBR\" =~ /$veeamserver/)"
   },
   {
    "name": "veeamversionM",
    "query": "select last(\"veeamBackupServersVersionM\") from (select \"veeamBackupServersPort\",\"veeamBackupServersVersionM\" from \"veeam_em_backup_servers\" WHERE $timeFilter AND \"veeamVBR\" =~ /$veeamserver/)"
   },
   {
    "name": "veeamagent",
    "label": "Veeam Agent",
    "query": "select DISTINCT(\"veeamAgentName\") from (select \"veeamAgentHostStatus\",\"veeamAgentName\" from \"veeam_em_agents\" WHERE $timeFilter AND \"veeamVBR\" =~ /$veeamserver/)"
   },
   {
    "name": "veeamnas",
    "label": "NAS",
    "query": "select DISTINCT(\"veeamNASJobPath\") from (select \"veeamNASJobShortTerm\",\"veeamNASJobPath\" from \"veeam_em_nas_jobs\" WHERE $timeFilter AND \"veeamVBR\" =~ /$veeamserver/)"
   },
   {
    "name": "veeamnasjob",
    "label": "NAS  Job",
    "query": "select DISTINCT(\"veeamNASJobName\") from (select \"veeamNASJobDuration\",\"veeamNASJobName\" from \"veeam_em_nas_sessions\" WHERE $timeFilter AND \"veeamVBR\" =~ /$veeamserver/)"
   },
   {
    "name": "backuptype",
    "label": "Job Type",
    "query": "select DISTINCT(\"veeamBackupSessionsJobType\") from (select \"veeamBackupSessionsJobResult\",\"veeamBackupSessionsJobType\" from \"veeam_em_job_sessions\" WHERE $timeFilter AND \"veeamVBR\" =~ /$veeamserver/)"
   }
  ]
 },
 "panels": [
  { "title": "Enterprise Manager - Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Backup Servers",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_em_overview",
     "query": "SELECT last(\"uptime_latest\") FROM \"vsphere_host_sys\" WHERE (\"esxhostname\" =~ /^$esxi$/ AND \"vcenter\" =~ /^$vcenter$/ AND \"clustername\" =~ /^$clustername$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "veeamBackupServers" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$enterprisemanager$/" }
     ]
    },
    {
     "alias": "Repository Servers",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_em_overview",
     "query": "SELECT last(\"uptime_latest\") FROM \"vsphere_host_sys\" WHERE (\"esxhostname\" =~ /^$esxi$/ AND \"vcenter\" =~ /^$vcenter$/ AND \"clustername\" =~ /^$clustername$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "veeamRepositoryServers" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$enterprisemanager$/" }
     ]
    },
    {
     "alias": "Proxy Servers",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_em_overview",
     "query": "SELECT last(\"uptime_latest\") FROM \"vsphere_host_sys\" WHERE (\"esxhostname\" =~ /^$esxi$/ AND \"vcenter\" =~ /^$vcenter$/ AND \"clustername\" =~ /^$clustername$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "veeamProxyServers" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$enterprisemanager$/" }
     ]
    },
    {
     "alias": "Protected VMs",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_em_overview_vms",
     "query": "SELECT last(\"uptime_latest\") FROM \"vsphere_host_sys\" WHERE (\"esxhostname\" =~ /^$esxi$/ AND \"vcenter\" =~ /^$vcenter$/ AND \"clustername\" =~ /^$clustername$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "veeamProtectedVms" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$enterprisemanager$/" }
     ]
    },
    {
     "alias": "Replicated VMs",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_em_overview_vms",
     "query": "SELECT last(\"uptime_latest\") FROM \"vsphere_host_sys\" WHERE (\"esxhostname\" =~ /^$esxi$/ AND \"vcenter\" =~ /^$vcenter$/ AND \"clustername\" =~ /^$clustername$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "veeamReplicatedVms" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$enterprisemanager$/" }
     ]
    },
    {
     "alias": "Successful Workloads",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_em_overview",
     "query": "SELECT last(\"uptime_latest\") FROM \"vsphere_host_sys\" WHERE (\"esxhostname\" =~ /^$esxi$/ AND \"vcenter\" =~ /^$vcenter$/ AND \"clustername\" =~ /^$clustername$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "veeamSuccessfulVmLastestStates" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$enterprisemanager$/" }
     ]
    },
    {
     "alias": "Warning VMs",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_em_overview",
     "query": "SELECT last(\"uptime_latest\") FROM \"vsphere_host_sys\" WHERE (\"esxhostname\" =~ /^$esxi$/ AND \"vcenter\" =~ /^$vcenter$/ AND \"clustername\" =~ /^$clustername$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "veeamWarningVmLastestStates" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$enterprisemanager$/" }
     ]
    },
    {
     "alias": "Failed VMs",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_em_overview",
     "query": "SELECT last(\"uptime_latest\") FROM \"vsphere_host_sys\" WHERE (\"esxhostname\" =~ /^$esxi$/ AND \"vcenter\" =~ /^$vcenter$/ AND \"clustername\" =~ /^$clustername$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "veeamFailedVmLastestStates" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$enterprisemanager$/" }
     ]
    }
   ]
  },
  {
   "title": "Backup Repository - Usage Capacity",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_veeamRepositoryName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (mean(\"veeamRepositoryCapacity\") - mean(\"veeamRepositoryFreeSpace\")) * (100 / mean(\"veeamRepositoryCapacity\"))  FROM  \"veeam_em_overview_repositories\" WHERE (\"veeamRepositoryName\" =~ /^$repository$/) AND $timeFilter GROUP BY time($__interval), \"veeamRepositoryName\"  fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Backup Repositories - Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "$repository",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 10 },
     "repeat": "repository",
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "veeam_office365_repository",
       "query": "SELECT (mean(\"veeamRepositoryCapacity\") - mean(\"veeamRepositoryFreeSpace\")) * (100 / mean(\"veeamRepositoryCapacity\"))  FROM  \"veeam_em_overview_repositories\" WHERE (\"veeamRepositoryName\" =~ /^$repository$/ AND \"veeamVBR\" =~ /^$veeamserver$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "capacity" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "repository", "operator": "=~", "value": "/^$repository$/" }
       ]
      }
     ]
    },
    {
     "title": "$repository",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "veeam_office365_repository",
       "query": "SELECT (mean(\"veeamRepositoryCapacity\") - mean(\"veeamRepositoryFreeSpace\")) * (100 / mean(\"veeamRepositoryCapacity\"))  FROM  \"veeam_em_overview_repositories\" WHERE (\"veeamRepositoryName\" =~ /^$repository$/ AND \"veeamVBR\" =~ /^$veeamserver$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "capacity" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "repository", "operator": "=~", "value": "/^$repository$/" }
       ]
      }
     ]
    },
    {
     "title": "$repository",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "veeam_office365_repository",
       "query": "SELECT (mean(\"veeamRepositoryCapacity\") - mean(\"veeamRepositoryFreeSpace\")) * (100 / mean(\"veeamRepositoryCapacity\"))  FROM  \"veeam_em_overview_repositories\" WHERE (\"veeamRepositoryName\" =~ /^$repository$/ AND \"veeamVBR\" =~ /^$veeamserver$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "capacity" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "repository", "operator": "=~", "value": "/^$repository$/" }
       ]
      }
     ]
    },
    {
     "title": "$repository",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "veeam_office365_repository",
       "query": "SELECT (mean(\"veeamRepositoryCapacity\") - mean(\"veeamRepositoryFreeSpace\")) * (100 / mean(\"veeamRepositoryCapacity\"))  FROM  \"veeam_em_overview_repositories\" WHERE (\"veeamRepositoryName\" =~ /^$repository$/ AND \"veeamVBR\" =~ /^$veeamserver$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "capacity" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "repository", "operator": "=~", "value": "/^$repository$/" }
       ]
      }
     ]
    },
    {
     "title": "$repository",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "veeam_office365_repository",
       "query": "SELECT (mean(\"veeamRepositoryCapacity\") - mean(\"veeamRepositoryFreeSpace\")) * (100 / mean(\"veeamRepositoryCapacity\"))  FROM  \"veeam_em_overview_repositories\" WHERE (\"veeamRepositoryName\" =~ /^$repository$/ AND \"veeamVBR\" =~ /^$veeamserver$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "capacity" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "repository", "operator": "=~", "value": "/^$repository$/" }
       ]
      }
     ]
    },
    {
     "title": "$repository",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "veeam_office365_repository",
       "query": "SELECT (mean(\"veeamRepositoryCapacity\") - mean(\"veeamRepositoryFreeSpace\")) * (100 / mean(\"veeamRepositoryCapacity\"))  FROM  \"veeam_em_overview_repositories\" WHERE (\"veeamRepositoryName\" =~ /^$repository$/ AND \"veeamVBR\" =~ /^$veeamserver$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "capacity" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "repository", "operator": "=~", "value": "/^$repository$/" }
       ]
      }
     ]
    },
    {
     "title": "$repository",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "veeam_office365_repository",
       "query": "SELECT (mean(\"veeamRepositoryCapacity\") - mean(\"veeamRepositoryFreeSpace\")) * (100 / mean(\"veeamRepositoryCapacity\"))  FROM  \"veeam_em_overview_repositories\" WHERE (\"veeamRepositoryName\" =~ /^$repository$/ AND \"veeamVBR\" =~ /^$veeamserver$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "capacity" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "repository", "operator": "=~", "value": "/^$repository$/" }
       ]
      }
     ]
    },
    {
     "title": "$repository",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "veeam_office365_repository",
       "query": "SELECT (mean(\"veeamRepositoryCapacity\") - mean(\"veeamRepositoryFreeSpace\")) * (100 / mean(\"veeamRepositoryCapacity\"))  FROM  \"veeam_em_overview_repositories\" WHERE (\"veeamRepositoryName\" =~ /^$repository$/ AND \"veeamVBR\" =~ /^$veeamserver$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "capacity" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "repository", "operator": "=~", "value": "/^$repository$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "$veeamserver v$veeamversionM ($veeamversion) - Veeam Backup Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "repeat": "veeamserver",
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "percent", "label": "CPU Usage in %" }
     ],
     "targets": [
      {
       "alias": "$tag_host $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "win_cpu",
       "select": [
        [
         { "params": [ "Percent_Privileged_Time" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "% Privileged Time" ], "type": "alias" }
        ],
        [
         { "params": [ "Percent_User_Time" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "% User Time" ], "type": "alias" }
        ],
        [
         { "params": [ "Percent_Interrupt_Time" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "% Interrupt Time" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$veeamserver$/" }
       ]
      }
     ]
    },
    {
     "title": "RAM Usage",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "decbytes", "label": "RAM Usage in bytes" }
     ],
     "targets": [
      {
       "alias": "$tag_host $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "win_mem",
       "select": [
        [
         { "params": [ "Available_Bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Available Bytes" ], "type": "alias" }
        ],
        [
         { "params": [ "Pool_Nonpaged_Bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Pool non-paged Bytes" ], "type": "alias" }
        ],
        [
         { "params": [ "Pool_Paged_Bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Pool paged Bytes" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$veeamserver$/" }
       ]
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "measurement": "win_system",
       "query": "SELECT \"System_Up_Time\" FROM \"win_system\" WHERE (\"host\" =~ /^$vboserver$/) AND $timeFilter",
       "select": [
        [
         { "params": [ "System_Up_Time" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$veeamserver$/" }
       ]
      }
     ]
    },
    {
     "title": "Disk Usage",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 10, "x": 3, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "$tag_instance",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "instance" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "win_disk",
       "query": "SELECT 100 - (mean(\"Percent_Free_Space\")) FROM \"win_disk\" WHERE (\"host\" =~ /^$veeamserver$/ ) AND (\"instance\" !='HarddiskVolume1') AND $timeFilter GROUP BY time($__interval), \"instance\" fill(linear)",
       "select": [
        [
         { "params": [ "Percent_Free_Space" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$vboserver$/" },
        { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$disk$/" }
       ]
      }
     ]
    },
    {
     "title": "Network Usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 11, "x": 13, "y": 16 },
     "yaxes": [
      { "format": "decbytes", "label": "Net Usage in bytes" }
     ],
     "targets": [
      {
       "alias": "$tag_host $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "win_net",
       "select": [
        [
         { "params": [ "Bytes_Received_persec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Bytes received" ], "type": "alias" }
        ],
        [
         { "params": [ "Bytes_Sent_persec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Bytes sent" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$veeamserver$/" },
        { "condition": "AND", "key": "instance", "operator": "=", "value": "vmxnet3 Ethernet Adapter _2" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "$veeamserver v$veeamversionM ($veeamversion) - Backup Jobs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "repeat": "veeamserver",
   "collapsed": true,
   "panels": [
    {
     "title": "$backupjob - Last Result",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 12 },
     "repeat": "backupjob",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_veeamBackupSessionsName",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "veeamBackupSessionsName" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "veeam_em_job_sessions",
       "query": "SELECT last(\"uptime_latest\") FROM \"vsphere_host_sys\" WHERE (\"esxhostname\" =~ /^$esxi$/ AND \"vcenter\" =~ /^$vcenter$/ AND \"clustername\" =~ /^$clustername$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "veeamBackupSessionsJobResult" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "veeamBackupSessionsName", "operator": "=~", "value": "/^$backupjob$/" },
        { "condition": "AND", "key": "veeamVBR", "operator": "=~", "value": "/^$veeamserver$/" },
        { "condition": "AND", "key": "veeamBackupSessionsJobType", "operator": "=~", "value": "/^$backuptype$/" }
       ]
      }
     ]
    },
    {
     "title": "$backupjob - Last Result",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_veeamBackupSessionsName",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "veeamBackupSessionsName" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "veeam_em_job_sessions",
       "query": "SELECT last(\"uptime_latest\") FROM \"vsphere_host_sys\" WHERE (\"esxhostname\" =~ /^$esxi$/ AND \"vcenter\" =~ /^$vcenter$/ AND \"clustername\" =~ /^$clustername$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "veeamBackupSessionsJobResult" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "veeamBackupSessionsName", "operator": "=~", "value": "/^$backupjob$/" },
        { "condition": "AND", "key": "veeamVBR", "operator": "=~", "value": "/^$veeamserver$/" },
        { "condition": "AND", "key": "veeamBackupSessionsJobType", "operator": "=~", "value": "/^$backuptype$/" }
       ]
      }
     ]
    },
    {
     "title": "$backupjob - Last Result",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_veeamBackupSessionsName",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "veeamBackupSessionsName" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "veeam_em_job_sessions",
       "query": "SELECT last(\"uptime_latest\") FROM \"vsphere_host_sys\" WHERE (\"esxhostname\" =~ /^$esxi$/ AND \"vcenter\" =~ /^$vcenter$/ AND \"clustername\" =~ /^$clustername$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "veeamBackupSessionsJobResult" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "veeamBackupSessionsName", "operator": "=~", "value": "/^$backupjob$/" },
        { "condition": "AND", "key": "veeamVBR", "operator": "=~", "value": "/^$veeamserver$/" },
        { "condition": "AND", "key": "veeamBackupSessionsJobType", "operator": "=~", "value": "/^$backuptype$/" }
       ]
      }
     ]
    },
    {
     "title": "$backupjob - Last Result",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_veeamBackupSessionsName",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "veeamBackupSessionsName" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "veeam_em_job_sessions",
       "query": "SELECT last(\"uptime_latest\") FROM \"vsphere_host_sys\" WHERE (\"esxhostname\" =~ /^$esxi$/ AND \"vcenter\" =~ /^$vcenter$/ AND \"clustername\" =~ /^$clustername$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "veeamBackupSessionsJobResult" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "veeamBackupSessionsName", "operator": "=~", "value": "/^$backupjob$/" },
        { "condition": "AND", "key": "veeamVBR", "operator": "=~", "value": "/^$veeamserver$/" },
        { "condition": "AND", "key": "veeamBackupSessionsJobType", "operator": "=~", "value": "/^$backuptype$/" }
       ]
      }
     ]
    },
    {
     "title": "$backupjob - Last Result",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_veeamBackupSessionsName",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "veeamBackupSessionsName" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "veeam_em_job_sessions",
       "query": "SELECT last(\"uptime_latest\") FROM \"vsphere_host_sys\" WHERE (\"esxhostname\" =~ /^$esxi$/ AND \"vcenter\" =~ /^$vcenter$/ AND \"clustername\" =~ /^$clustername$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "veeamBackupSessionsJobResult" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "veeamBackupSessionsName", "operator": "=~", "value": "/^$backupjob$/" },
        { "condition": "AND", "key": "veeamVBR", "operator": "=~", "value": "/^$veeamserver$/" },
        { "condition": "AND", "key": "veeamBackupSessionsJobType", "operator": "=~", "value": "/^$backuptype$/" }
       ]
      }
     ]
    },
    {
     "title": "$backupjob - Last Result",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_veeamBackupSessionsName",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "veeamBackupSessionsName" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "veeam_em_job_sessions",
       "query": "SELECT last(\"uptime_latest\") FROM \"vsphere_host_sys\" WHERE (\"esxhostname\" =~ /^$esxi$/ AND \"vcenter\" =~ /^$vcenter$/ AND \"clustername\" =~ /^$clustername$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "veeamBackupSessionsJobResult" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "veeamBackupSessionsName", "operator": "=~", "value": "/^$backupjob$/" },
        { "condition": "AND", "key": "veeamVBR", "operator": "=~", "value": "/^$veeamserver$/" },
        { "condition": "AND", "key": "veeamBackupSessionsJobType", "operator": "=~", "value": "/^$backuptype$/" }
       ]
      }
     ]
    },
    {
     "title": "$backupjob - Last Result",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_veeamBackupSessionsName",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "veeamBackupSessionsName" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "veeam_em_job_sessions",
       "query": "SELECT last(\"uptime_latest\") FROM \"vsphere_host_sys\" WHERE (\"esxhostname\" =~ /^$esxi$/ AND \"vcenter\" =~ /^$vcenter$/ AND \"clustername\" =~ /^$clustername$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "veeamBackupSessionsJobResult" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "veeamBackupSessionsName", "operator": "=~", "value": "/^$backupjob$/" },
        { "condition": "AND", "key": "veeamVBR", "operator": "=~", "value": "/^$veeamserver$/" },
        { "condition": "AND", "key": "veeamBackupSessionsJobType", "operator": "=~", "value": "/^$backuptype$/" }
       ]
      }
     ]
    },
    {
     "title": "$backupjob - Last Result",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_veeamBackupSessionsName",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "veeamBackupSessionsName" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "veeam_em_job_sessions",
       "query": "SELECT last(\"uptime_latest\") FROM \"vsphere_host_sys\" WHERE (\"esxhostname\" =~ /^$esxi$/ AND \"vcenter\" =~ /^$vcenter$/ AND \"clustername\" =~ /^$clustername$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "veeamBackupSessionsJobResult" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "veeamBackupSessionsName", "operator": "=~", "value": "/^$backupjob$/" },
        { "condition": "AND", "key": "veeamVBR", "operator": "=~", "value": "/^$veeamserver$/" },
        { "condition": "AND", "key": "veeamBackupSessionsJobType", "operator": "=~", "value": "/^$backuptype$/" }
       ]
      }
     ]
    },
    {
     "title": "$backupjob - Last Result",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_veeamBackupSessionsName",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "veeamBackupSessionsName" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "veeam_em_job_sessions",
       "query": "SELECT last(\"uptime_latest\") FROM \"vsphere_host_sys\" WHERE (\"esxhostname\" =~ /^$esxi$/ AND \"vcenter\" =~ /^$vcenter$/ AND \"clustername\" =~ /^$clustername$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "veeamBackupSessionsJobResult" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "veeamBackupSessionsName", "operator": "=~", "value": "/^$backupjob$/" },
        { "condition": "AND", "key": "veeamVBR", "operator": "=~", "value": "/^$veeamserver$/" },
        { "condition": "AND", "key": "veeamBackupSessionsJobType", "operator": "=~", "value": "/^$backuptype$/" }
       ]
      }
     ]
    },
    {
     "title": "$backupjob - Last Result",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_veeamBackupSessionsName",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "veeamBackupSessionsName" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "veeam_em_job_sessions",
       "query": "SELECT last(\"uptime_latest\") FROM \"vsphere_host_sys\" WHERE (\"esxhostname\" =~ /^$esxi$/ AND \"vcenter\" =~ /^$vcenter$/ AND \"clustername\" =~ /^$clustername$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "veeamBackupSessionsJobResult" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "veeamBackupSessionsName", "operator": "=~", "value": "/^$backupjob$/" },
        { "condition": "AND", "key": "veeamVBR", "operator": "=~", "value": "/^$veeamserver$/" },
        { "condition": "AND", "key": "veeamBackupSessionsJobType", "operator": "=~", "value": "/^$backuptype$/" }
       ]
      }
     ]
    },
    {
     "title": "$backupjob - Last Result",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_veeamBackupSessionsName",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "veeamBackupSessionsName" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "veeam_em_job_sessions",
       "query": "SELECT last(\"uptime_latest\") FROM \"vsphere_host_sys\" WHERE (\"esxhostname\" =~ /^$esxi$/ AND \"vcenter\" =~ /^$vcenter$/ AND \"clustername\" =~ /^$clustername$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "veeamBackupSessionsJobResult" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "veeamBackupSessionsName", "operator": "=~", "value": "/^$backupjob$/" },
        { "condition": "AND", "key": "veeamVBR", "operator": "=~", "value": "/^$veeamserver$/" },
        { "condition": "AND", "key": "veeamBackupSessionsJobType", "operator": "=~", "value": "/^$backuptype$/" }
       ]
      }
     ]
    },
    {
     "title": "$backupjob - Last Result",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_veeamBackupSessionsName",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "veeamBackupSessionsName" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "veeam_em_job_sessions",
       "query": "SELECT last(\"uptime_latest\") FROM \"vsphere_host_sys\" WHERE (\"esxhostname\" =~ /^$esxi$/ AND \"vcenter\" =~ /^$vcenter$/ AND \"clustername\" =~ /^$clustername$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "veeamBackupSessionsJobResult" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "veeamBackupSessionsName", "operator": "=~", "value": "/^$backupjob$/" },
        { "condition": "AND", "key": "veeamVBR", "operator": "=~", "value": "/^$veeamserver$/" },
        { "condition": "AND", "key": "veeamBackupSessionsJobType", "operator": "=~", "value": "/^$backuptype$/" }
       ]
      }
     ]
    },
    {
     "title": "$backupjob - Last Result",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_veeamBackupSessionsName",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "veeamBackupSessionsName" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "veeam_em_job_sessions",
       "query": "SELECT last(\"uptime_latest\") FROM \"vsphere_host_sys\" WHERE (\"esxhostname\" =~ /^$esxi$/ AND \"vcenter\" =~ /^$vcenter$/ AND \"clustername\" =~ /^$clustername$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "veeamBackupSessionsJobResult" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "veeamBackupSessionsName", "operator": "=~", "value": "/^$backupjob$/" },
        { "condition": "AND", "key": "veeamVBR", "operator": "=~", "value": "/^$veeamserver$/" },
        { "condition": "AND", "key": "veeamBackupSessionsJobType", "operator": "=~", "value": "/^$backuptype$/" }
       ]
      }
     ]
    },
    {
     "title": "$backupjob - Last Result",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_veeamBackupSessionsName",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "veeamBackupSessionsName" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "veeam_em_job_sessions",
       "query": "SELECT last(\"uptime_latest\") FROM \"vsphere_host_sys\" WHERE (\"esxhostname\" =~ /^$esxi$/ AND \"vcenter\" =~ /^$vcenter$/ AND \"clustername\" =~ /^$clustername$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "veeamBackupSessionsJobResult" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "veeamBackupSessionsName", "operator": "=~", "value": "/^$backupjob$/" },
        { "condition": "AND", "key": "veeamVBR", "operator": "=~", "value": "/^$veeamserver$/" },
        { "condition": "AND", "key": "veeamBackupSessionsJobType", "operator": "=~", "value": "/^$backuptype$/" }
       ]
      }
     ]
    },
    {
     "title": "$backupjob - Last Result",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_veeamBackupSessionsName",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "veeamBackupSessionsName" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "veeam_em_job_sessions",
       "query": "SELECT last(\"uptime_latest\") FROM \"vsphere_host_sys\" WHERE (\"esxhostname\" =~ /^$esxi$/ AND \"vcenter\" =~ /^$vcenter$/ AND \"clustername\" =~ /^$clustername$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "veeamBackupSessionsJobResult" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "veeamBackupSessionsName", "operator": "=~", "value": "/^$backupjob$/" },
        { "condition": "AND", "key": "veeamVBR", "operator": "=~", "value": "/^$veeamserver$/" },
        { "condition": "AND", "key": "veeamBackupSessionsJobType", "operator": "=~", "value": "/^$backuptype$/" }
       ]
      }
     ]
    },
    {
     "title": "$backupjob - Last Result",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_veeamBackupSessionsName",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "veeamBackupSessionsName" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "veeam_em_job_sessions",
       "query": "SELECT last(\"uptime_latest\") FROM \"vsphere_host_sys\" WHERE (\"esxhostname\" =~ /^$esxi$/ AND \"vcenter\" =~ /^$vcenter$/ AND \"clustername\" =~ /^$clustername$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "veeamBackupSessionsJobResult" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "veeamBackupSessionsName", "operator": "=~", "value": "/^$backupjob$/" },
        { "condition": "AND", "key": "veeamVBR", "operator": "=~", "value": "/^$veeamserver$/" },
        { "condition": "AND", "key": "veeamBackupSessionsJobType", "operator": "=~", "value": "/^$backuptype$/" }
       ]
      }
     ]
    },
    {
     "title": "$backupjob - Last Result",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_veeamBackupSessionsName",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "veeamBackupSessionsName" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "veeam_em_job_sessions",
       "query": "SELECT last(\"uptime_latest\") FROM \"vsphere_host_sys\" WHERE (\"esxhostname\" =~ /^$esxi$/ AND \"vcenter\" =~ /^$vcenter$/ AND \"clustername\" =~ /^$clustername$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "veeamBackupSessionsJobResult" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "veeamBackupSessionsName", "operator": "=~", "value": "/^$backupjob$/" },
        { "condition": "AND", "key": "veeamVBR", "operator": "=~", "value": "/^$veeamserver$/" },
        { "condition": "AND", "key": "veeamBackupSessionsJobType", "operator": "=~", "value": "/^$backuptype$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "$veeamserver v$veeamversionM ($veeamversion) - Replica Jobs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "repeat": "veeamserver",
   "collapsed": true,
   "panels": [
    {
     "title": "$replicajob - Last Result",
     "type": "stat",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 13 },
     "repeat": "replicajob",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_veeamReplicaSessionsName",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "veeamReplicaSessionsName" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "veeam_em_job_sessions",
       "query": "SELECT last(\"veeamReplicaSessionsJobResult\") FROM \"veeam_em_job_sessions\" WHERE (\"veeamReplicaSessionsName\" =~ /^$replicajob$/ AND \"veeamVBR\" =~ /^$veeamserver$/) AND $timeFilter GROUP BY time($__interval), \"veeamReplicaSessionsName\" fill(none)",
       "select": [
        [
         { "params": [ "veeamReplicaSessionsJobResult" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "veeamReplicaSessionsName", "operator": "=~", "value": "/^$replicajob$/" },
        { "condition": "AND", "key": "veeamVBR", "operator": "=~", "value": "/^$veeamserver$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "$veeamserver v$veeamversionM ($veeamversion) - Protected VMs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "repeat": "veeamserver"
  },
  {
   "title": "$backupvm",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 14 },
   "repeat": "backupvm",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_veeamBackupSessionsVmDisplayName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      {
       "params": [
        "veeamBackupSessionsVmDisplayName"
       ],
       "type": "tag"
      },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "veeam_em_job_sessionsvm",
     "query": "SELECT last(\"veeamBackupSessionsJobVMResult\") FROM \"veeam_em_job_sessionsvm\" WHERE (\"veeamBackupSessionsVmDisplayName\" =~ /^$backupvm$/ AND \"veeamVBR\" =~ /^$veeamserver$/) AND $timeFilter GROUP BY time($__interval), \"veeamBackupSessionsVmDisplayName\" fill(none)",
     "select": [
      [
       { "params": [ "veeamBackupSessionsJobVMResult" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "veeamBackupSessionsVmDisplayName",
       "operator": "=~",
       "value": "/^$backupvm$/"
      },
      { "condition": "AND", "key": "veeamVBR", "operator": "=~", "value": "/^$veeamserver$/" }
     ]
    }
   ]
  },
  {
   "title": "$veeamserver v$veeamversionM ($veeamversion) - Replicated VMs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "repeat": "veeamserver",
   "collapsed": true,
   "panels": [
    {
     "title": "$replicavm",
     "type": "stat",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 15 },
     "repeat": "replicavm",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_veeamReplicaSessionsVmDisplayName",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        {
         "params": [
          "veeamReplicaSessionsVmDisplayName"
         ],
         "type": "tag"
        },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "veeam_em_job_sessionsvm",
       "select": [
        [
         {
          "params": [
           "veeamReplicaSessionsJobVMResult"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        {
         "key": "veeamReplicaSessionsVmDisplayName",
         "operator": "=~",
         "value": "/^$replicavm$/"
        }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "$veeamserver v$veeamversionM ($veeamversion) - Veeam Agents Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "repeat": "veeamserver"
  },
  {
   "title": "Veeam Agent Status and Information",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "alias": "$tag_veeamAgentName",
     "groupBy": [
      { "params": [ "veeamAgentName" ], "type": "tag" },
      { "params": [ "veeamAgentOsVersion" ], "type": "tag" },
      { "params": [ "veeamAgentVersion" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "veeam_em_agents",
     "select": [
      [
       { "params": [ "veeamAgentStatus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "agentstatus" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "veeamAgentName", "operator": "=~", "value": "/^$veeamagent$/" },
      { "condition": "AND", "key": "veeamVBR", "operator": "=~", "value": "/^$veeamserver$/" }
     ]
    },
    {
     "alias": "$tag_veeamAgentName",
     "groupBy": [
      { "params": [ "veeamAgentName" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "veeam_em_agents",
     "select": [
      [
       { "params": [ "veeamAgentHostStatus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "agenthoststatus" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "veeamAgentName", "operator": "=~", "value": "/^$veeamagent$/" },
      { "condition": "AND", "key": "veeamVBR", "operator": "=~", "value": "/^$veeamserver$/" }
     ]
    }
   ]
  },
  {
   "title": "$veeamserver v$veeamversionM ($veeamversion) - Veeam NAS Backup Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "repeat": "veeamserver",
   "collapsed": true,
   "panels": [
    {
     "title": "Veeam Agent Status and Information",
     "type": "table",
     "gridPos": { "h": 9, "w": 13, "x": 0, "y": 17 },
     "targets": [
      {
       "alias": "$tag_veeamAgentName",
       "groupBy": [
        { "params": [ "veeamNASJobName" ], "type": "tag" },
        { "params": [ "veeamNASJobPath" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "veeam_em_nas_jobs",
       "select": [
        [
         { "params": [ "veeamNASJobShortTerm" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Short-Term" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "veeamNASJobPath", "operator": "=~", "value": "/^$veeamnas$/" },
        { "condition": "AND", "key": "veeamVBR", "operator": "=~", "value": "/^$veeamserver$/" }
       ]
      },
      {
       "alias": "$tag_veeamAgentName",
       "groupBy": [
        { "params": [ "veeamNASJobShortTermType" ], "type": "tag" },
        { "params": [ "veeamNASJobExclusions" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "veeam_em_nas_jobs",
       "select": [
        [
         { "params": [ "veeamNASJobShortTerm" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Short-Term" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "veeamNASJobPath", "operator": "=~", "value": "/^$veeamnas$/" },
        { "condition": "AND", "key": "veeamVBR", "operator": "=~", "value": "/^$veeamserver$/" }
       ]
      }
     ]
    },
    {
     "title": "Job Duration",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 13, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "alias": "$tag_veeamNASJobName",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "veeamNASJobName" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "veeam_em_nas_sessions",
       "select": [
        [
         { "params": [ "veeamNASJobDuration" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "veeamNASJobName", "operator": "=~", "value": "/^$veeamnasjob$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "$veeamserver v$veeamversionM ($veeamversion) - Job Historical Performance and Duration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "repeat": "veeamserver"
  },
  {
   "title": "Job Historical Information",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_veeamBackupSessionsName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "veeamBackupSessionsName" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "veeam_em_job_sessions",
     "select": [
      [
       { "params": [ "veeamBackupSessionsJobResult" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "veeamBackupSessionsName", "operator": "=~", "value": "/^$backupjob$/" },
      { "condition": "AND", "key": "veeamVBR", "operator": "=~", "value": "/^$veeamserver$/" },
      { "condition": "AND", "key": "veeamBackupSessionsJobType", "operator": "=~", "value": "/^$backuptype$/" }
     ]
    }
   ]
  },
  {
   "title": "Job Duration (All type)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "$tag_veeamBackupSessionsName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "veeamBackupSessionsName" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "veeam_em_job_sessions",
     "select": [
      [
       {
        "params": [
         "veeamBackupSessionsTimeDuration"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "veeamBackupSessionsName", "operator": "=~", "value": "/^$backupjob$/" },
      { "condition": "AND", "key": "veeamVBR", "operator": "=~", "value": "/^$veeamserver$/" },
      { "condition": "AND", "key": "veeamBackupSessionsJobType", "operator": "=~", "value": "/^$backuptype$/" }
     ]
    },
    {
     "alias": "$tag_veeamReplicaSessionsName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "veeamReplicaSessionsName" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "veeam_em_job_sessions",
     "select": [
      [
       { "params": [ "veeamReplicaSessionsDuration" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "veeamReplicaSessionsName", "operator": "=~", "value": "/^$replicajob$/" },
      { "condition": "AND", "key": "veeamVBR", "operator": "=~", "value": "/^$veeamserver$/" }
     ]
    }
   ]
  }
 ]
}