{
 "title": "Grafana Dashboard for Veeam Backup for AWS",
 "description": "Grafana Dashboard for Veeam Backup for AWS v4 (Grafana 8.x / InfluxDB v2.x)",
 "tags": [
  "veeam",
  "aws",
  "vba"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "PolicyName",
    "label": "Policy Name",
    "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_aws_sessions\")\r\n  |> keep(columns: [\"sessionPolicyJobName\"])\r\n  |> distinct(column: \"sessionPolicyJobName\")\r\n  |> group()"
   },
   {
    "name": "VMName",
    "label": "Unprotected VM",
    "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_aws_vm_unprotected\")\r\n  |> filter(fn: (r) => r[\"VMName\"] != \"\")\r\n  |> keep(columns: [\"VMName\"])\r\n  |> distinct(column: \"VMName\")\r\n  |> group()"
   },
   {
    "name": "Repository",
    "label": "Blob Repository",
    "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_aws_repositories\")\r\n  |> filter(fn: (r) => r[\"repoName\"] != \"\")\r\n  |> keep(columns: [\"repoName\"])\r\n  |> distinct(column: \"repoName\")\r\n  |> group()"
   },
   {
    "name": "PolicyType",
    "label": "Policy Type",
    "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_aws_sessions\")\r\n  |> filter(fn: (r) => r[\"sessionType\"] != \"\")\r\n  |> keep(columns: [\"sessionType\"])\r\n  |> distinct(column: \"sessionType\")\r\n  |> group()"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 0, "y": 0 },
   "options": {
    "content": "<a href=\"https://www.veeam.com/backup-azure.html\" target=\"_blank\"><img src=\"https://www.jorgedelacruz.es/VCB_product_icon.svg\" alt=\"drawing\" width=\"50\"/></a>\n\n"
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 15, "x": 1, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Total Policies",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_aws_overview",
     "query": "  from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_aws_overview\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Policies\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "Policies" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Total Repositories",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_aws_overview",
     "query": "  from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_aws_overview\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Repositories\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "Repositories" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Protected Instances",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_aws_overview",
     "query": "  from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_aws_overview\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"VMs\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "VMs" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Version $tag_version",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "version" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "veeam_aws_overview",
     "query": "  from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_aws_overview\")\n  |> filter(fn: (r) => r[\"_field\"] == \"InstancesUsed\")\n  |> group(columns: [\"version\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n",
     "select": [
      [
       { "params": [ "InstancesUsed" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "License: $tag_LicenseType",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "LicenseType" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "veeam_aws_overview",
     "query": "  from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_aws_overview\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"InstancesUsed\")\r\n  |> group(columns: [\"LicenseType\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)",
     "select": [
      [
       { "params": [ "InstancesUsed" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Unprotected VMs",
   "type": "geomap",
   "description": "On this Map, you can quickly know which VMs are not Protected by Veeam Backup for AWS. \nWith a simple, yet powerful view, you can understand and try to mitigate the red spots.",
   "gridPos": { "h": 16, "w": 11, "x": 0, "y": 2 },
   "targets": [
    {
     "alias": "$tag_geohash",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "geohash" ], "type": "tag" },
      { "params": [ "VMRegion" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "veeam_aws_vm_unprotected",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_aws_vm_unprotected\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"UPVM\" and r._value >=1)\r\n  |> group(columns: [\"geohash\",\"VMRegion\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "UPVM" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Unprotected VMs" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Protected VMs Overview",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 5, "x": 11, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Protected VMs",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "veeam_aws_vm_protected",
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_aws_vm_protected\")\n  |> filter(fn: (r) => r[\"_field\"] == \"TotalVMs\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")\n",
     "select": [
      [
       { "params": [ "TotalVMs" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Unprotected VMs",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "veeam_aws_vm_unprotected",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_aws_vm_unprotected\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"TotalVMs\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")\r\n",
     "select": [
      [
       { "params": [ "TotalVMs" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Job and Policies Duration",
   "type": "timeseries",
   "description": "On this Panel, you can quickly know how much time did a Backup, or Snapshot Policy take. You can quickly filter by Policy Name on the top menu.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_sessionPolicyJobName - $tag_sessionType",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sessionPolicyJobName" ], "type": "tag" },
      { "params": [ "sessionType" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "veeam_aws_sessions",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_aws_sessions\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"sessionDuration\")\r\n  |> filter(fn: (r) => r[\"sessionType\"] =~ /${PolicyType:regex}/)\r\n  |> filter(fn: (r) => r[\"sessionPolicyJobName\"] =~ /${PolicyName:regex}/)\r\n  |> group(columns: [\"sessionPolicyJobName\",\"sessionType\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n\r\n",
     "select": [
      [
       { "params": [ "sessionDuration" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sessionType", "operator": "=~", "value": "/^$PolicyType$/" },
      { "condition": "AND", "key": "sessionPolicyJobName", "operator": "=~", "value": "/^$PolicyName$/" }
     ]
    }
   ]
  },
  {
   "title": "Job Historical Information",
   "type": "table",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_sessionPolicyName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sessionPolicyName" ], "type": "tag" },
      { "params": [ "sessionType" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "veeam_aws_sessions",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_aws_sessions\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"sessionStatus\")\r\n  |> filter(fn: (r) => r[\"sessionPolicyJobName\"] =~ /${PolicyName:regex}/)\r\n  |> group(columns: [\"sessionPolicyJobName\",\"sessionType\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n",
     "select": [
      [
       { "params": [ "sessionStatus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sessionPolicyName", "operator": "=~", "value": "/^$PolicyName$/" }
     ]
    }
   ]
  },
  {
   "title": "Protected Resources & Inventory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 }
  },
  {
   "title": "Protected Amazon VPC",
   "type": "table",
   "description": "On this Panel, you can quickly list all your protected VPC on the different Regions",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "vpcid" ], "type": "tag" },
      { "params": [ "vpcregion" ], "type": "tag" }
     ],
     "measurement": "veeam_aws_vpc",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_aws_vpc\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"vpcprotected\")\r\n  |> group(columns: [\"vpcid\",\"vpcregion\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n",
     "select": [
      [
       { "params": [ "vpcprotected" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "RDS  Size" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Protected VMs",
   "type": "table",
   "description": "On this Panel, you can quickly list all your Protected EC2 Instances",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "VMName" ], "type": "tag" },
      { "params": [ "VMRegion" ], "type": "tag" },
      { "params": [ "VMType" ], "type": "tag" }
     ],
     "measurement": "veeam_aws_vm",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_aws_vm\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"VMSize\")\r\n  |> group(columns: [\"VMName\",\"VMRegion\",\"VMType\"])\r\n  |> last()",
     "select": [
      [
       { "params": [ "VMSize" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "VM  Size" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Unprotected VMs",
   "type": "table",
   "description": "On this Panel, you can quickly list all your unprotected EC2 Instances",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "VMName" ], "type": "tag" },
      { "params": [ "VMRegion" ], "type": "tag" },
      { "params": [ "VMType" ], "type": "tag" }
     ],
     "measurement": "veeam_aws_vm_unprotected",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_aws_vm_unprotected\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"VMSize\")\r\n  |> group(columns: [\"VMName\",\"VMRegion\",\"VMType\"])\r\n  |> last()",
     "select": [
      [
       { "params": [ "VMSize" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "VM  Size" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Protected Amazon RDS",
   "type": "table",
   "description": "On this Panel, you can quickly list all your protected RDS Instances",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "rdsname" ], "type": "tag" },
      { "params": [ "rdsclass" ], "type": "tag" },
      { "params": [ "rdsengine" ], "type": "tag" },
      { "params": [ "rdsengineversion" ], "type": "tag" },
      { "params": [ "rdsregion" ], "type": "tag" },
      { "params": [ "rdsdns" ], "type": "tag" }
     ],
     "measurement": "veeam_aws_rds",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_aws_rds\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"rdssize\")\r\n  |> group(columns: [\"rdsname\",\"rdsclass\",\"rdsengine\",\"rdsengineversion\",\"rdsregion\",\"rdsdns\"])\r\n  |> last()",
     "select": [
      [
       { "params": [ "rdssize" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "RDS  Size" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Protected Amazon EFS",
   "type": "table",
   "description": "On this Panel, you can quickly list all your protected EFS Instances",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "efsname" ], "type": "tag" },
      { "params": [ "efsperformance" ], "type": "tag" },
      { "params": [ "efsregion" ], "type": "tag" },
      { "params": [ "efsawsid" ], "type": "tag" }
     ],
     "measurement": "veeam_aws_efs",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_aws_efs\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"rdssize\")\r\n  |> group(columns: [\"efsname\",\"efsperformance\",\"efsregion\",\"efsawsid\"])\r\n  |> last()",
     "select": [
      [
       { "params": [ "rdssize" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "RDS  Size" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Veeam Backup for AWS Repositories",
   "type": "table",
   "description": "On this Panel, you can quickly list all your repositories, with their bucket location, folder, region, and if the Encryption is enabled or not.",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "repoBucket" ], "type": "tag" },
      { "params": [ "repoDescription" ], "type": "tag" },
      { "params": [ "repoFolderName" ], "type": "tag" },
      { "params": [ "repoName" ], "type": "tag" },
      { "params": [ "repoRegion" ], "type": "tag" }
     ],
     "measurement": "veeam_aws_repositories",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_aws_repositories\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"repoEncryption\")\r\n  |> group(columns: [\"repoBucket\",\"repoDescription\",\"repoFolderName\",\"repoName\",\"repoRegion\"])\r\n  |> last()",
     "select": [
      [
       { "params": [ "repoEncryption" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Encryption" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Veeam Backup for AWS Policies",
   "type": "table",
   "description": "On this Panel, you can quickly list all your Policies.",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "PolicyDescription" ], "type": "tag" },
      { "params": [ "PolicyName" ], "type": "tag" },
      { "params": [ "PolicyStatus" ], "type": "tag" },
      { "params": [ "PolicyType" ], "type": "tag" }
     ],
     "measurement": "veeam_aws_policies",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_aws_policies\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"PolicySnapshotCount\")\r\n  |> group(columns: [\"PolicyDescription\",\"PolicyName\",\"PolicyStatus\",\"PolicyType\"])\r\n  |> last()",
     "select": [
      [
       { "params": [ "PolicySnapshotCount" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Restore Points" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 48 },
   "options": {
    "content": "<a href=\"https://www.jorgedelacruz.es\"><img src=\"https://www.jorgedelacruz.es/wp-content/uploads/2019/04/jorgedelacruz-banner_2efede4ef704c939e63a3763231f5961.png\"></a>\n\n\n\n"
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}