{
 "title": "Grafana Dashboard for Veeam Availability Console - Tenant Overview",
 "description": "Grafana Dashboard for Veeam Availability Console - Tenant Overview",
 "tags": [
  "Veeam",
  "Veeam Availability Console",
  "VAC - Tenant Overview"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "inter",
    "label": "Sampling",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "tenant",
    "label": "Tenant",
    "query": "SHOW TAG VALUES FROM veeam_vac_tenant WITH KEY=companyName"
   },
   {
    "name": "vbrserver",
    "label": "On-prem VBR",
    "query": "SHOW TAG VALUES FROM veeam_vac_vbrlicense WITH KEY=backupServerName"
   },
   {
    "name": "job",
    "label": "Backup Job",
    "query": "SHOW TAG VALUES FROM veeam_vac_jobs WITH KEY=veeamjobname"
   }
  ]
 },
 "panels": [
  { "title": "$tenant Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "tenant" },
  {
   "title": "Expiration Date",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "dateTimeFromNow",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_vac_tenant",
     "select": [
      [
       { "params": [ "expirationDate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "companyName", "operator": "=~", "value": "/^$tenant$/" }
     ]
    }
   ]
  },
  {
   "title": "Storage Quota",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "format": "decmbytes",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_vac_backupresources",
     "select": [
      [
       { "params": [ "storageQuota" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "companyName", "operator": "=~", "value": "/^$tenant$/" }
     ]
    }
   ]
  },
  {
   "title": "VMs with Backup - Cloud",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_vac_tenant",
     "select": [
      [
       { "params": [ "vMsBackedUpToCloud" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "companyName", "operator": "=~", "value": "/^$tenant$/" }
     ]
    }
   ]
  },
  {
   "title": "Managed Cloud Servers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_vac_tenant",
     "select": [
      [
       { "params": [ "managedCloudServers" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "companyName", "operator": "=~", "value": "/^$tenant$/" }
     ]
    }
   ]
  },
  {
   "title": "Managed Physical Servers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_vac_tenant",
     "select": [
      [
       { "params": [ "managedPhysicalServers" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "companyName", "operator": "=~", "value": "/^$tenant$/" }
     ]
    }
   ]
  },
  {
   "title": "VMs with Backup",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_vac_tenant",
     "select": [
      [
       { "params": [ "vMsBackedUp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "companyName", "operator": "=~", "value": "/^$tenant$/" }
     ]
    }
   ]
  },
  {
   "title": "Cloud Repository - Usage Capacity",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "percent", "label": "Used Space" }
   ],
   "targets": [
    {
     "alias": "$tag_cloudRepositoryName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (mean(\"storageQuota\") - mean(\"usedStorageQuota\")) * (100 / mean(\"storageQuota\"))  FROM \"veeam_vac_backupresources\" WHERE (\"companyName\" =~ /^$tenant$/)AND $timeFilter GROUP BY time(5m), \"cloudRepositoryName\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 4 },
   "format": "MBs",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_vac_tenant",
     "query": "SELECT mean(\"allowedBandwidth\") FROM \"veeam_vac_tenant\" WHERE (\"companyName\" =~ /^$tenant$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "allowedBandwidth" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "companyName", "operator": "=~", "value": "/^$tenant$/" }
     ]
    }
   ]
  },
  {
   "title": "Max. Concurrent Tasks",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_vac_tenant",
     "select": [
      [
       { "params": [ "maxConcurrentTasks" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "companyName", "operator": "=~", "value": "/^$tenant$/" }
     ]
    }
   ]
  },
  {
   "title": "Traffic Quota",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 4 },
   "format": "decmbytes",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_vac_backupresources",
     "select": [
      [
       { "params": [ "trafficQuota" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "companyName", "operator": "=~", "value": "/^$tenant$/" }
     ]
    }
   ]
  },
  {
   "title": "WAN Acceleration",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "alias": "$tag_wanAccelerationEnabled",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "wanAccelerationEnabled" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_vac_backupresources",
     "select": [
      [
       { "params": [ "vMsQuota" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "companyName", "operator": "=~", "value": "/^$tenant$/" }
     ]
    }
   ]
  },
  {
   "title": "Managed Cloud Workstations",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_vac_tenant",
     "select": [
      [
       { "params": [ "managedCloudWorkstations" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "companyName", "operator": "=~", "value": "/^$tenant$/" }
     ]
    }
   ]
  },
  {
   "title": "Managed Physical Workstations",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_vac_tenant",
     "select": [
      [
       { "params": [ "managedPhysicalWorkstations" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "companyName", "operator": "=~", "value": "/^$tenant$/" }
     ]
    }
   ]
  },
  {
   "title": "VMs with Replica",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_vac_tenant",
     "select": [
      [
       { "params": [ "vMsReplicated" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "companyName", "operator": "=~", "value": "/^$tenant$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 7 },
   "content": "<img src=\"https://www.jorgedelacruz.es/wp-content/uploads/2019/01/onpremvbr-5.png\"></img>"
  },
  {
   "title": "Veeam Server Name",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 7 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "alias": "$tag_backupServerName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "backupServerName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_vac_vbrlicense",
     "select": [
      [
       { "params": [ "usedVMs" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "backupServerName", "operator": "=~", "value": "/^$vbrserver$/" },
      { "condition": "AND", "key": "companyName", "operator": "=~", "value": "/^$tenant$/" }
     ]
    }
   ]
  },
  {
   "title": "License Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 7 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "alias": "$tag_status",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "status" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_vac_vbrlicense",
     "select": [
      [
       { "params": [ "usedVMs" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "backupServerName", "operator": "=~", "value": "/^$vbrserver$/" },
      { "condition": "AND", "key": "companyName", "operator": "=~", "value": "/^$tenant$/" }
     ]
    }
   ]
  },
  {
   "title": "Licensed Sockets",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_vac_vbrlicense",
     "select": [
      [
       { "params": [ "licensedSockets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "companyName", "operator": "=~", "value": "/^$tenant$/" },
      { "condition": "AND", "key": "backupServerName", "operator": "=~", "value": "/^$vbrserver$/" }
     ]
    }
   ]
  },
  {
   "title": "Licensed VMs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_vac_vbrlicense",
     "select": [
      [
       { "params": [ "licensedVMs" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "companyName", "operator": "=~", "value": "/^$tenant$/" },
      { "condition": "AND", "key": "backupServerName", "operator": "=~", "value": "/^$vbrserver$/" }
     ]
    }
   ]
  },
  {
   "title": "Veeam Backup on-prem Repository - Usage Capacity",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 7 },
   "yaxes": [
    { "format": "percent", "label": "Used Space" }
   ],
   "targets": [
    {
     "alias": "$tag_repoName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (mean(\"capacity\") - mean(\"freeSpace\")) * (100 / mean(\"capacity\"))  FROM  \"veeam_vac_repositories\" WHERE (\"companyName\" =~ /^$tenant$/) AND $timeFilter GROUP BY time(5m), \"repoName\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Edition",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 10 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "alias": "$tag_edition",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "edition" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_vac_vbrlicense",
     "select": [
      [
       { "params": [ "usedVMs" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "backupServerName", "operator": "=~", "value": "/^$vbrserver$/" },
      { "condition": "AND", "key": "companyName", "operator": "=~", "value": "/^$tenant$/" }
     ]
    }
   ]
  },
  {
   "title": "Lic. Exp. Date",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 10 },
   "format": "dateTimeFromNow",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_vac_vbrlicense",
     "select": [
      [
       { "params": [ "licenseExpirationDate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "companyName", "operator": "=~", "value": "/^$tenant$/" },
      { "condition": "AND", "key": "backupServerName", "operator": "=~", "value": "/^$vbrserver$/" }
     ]
    }
   ]
  },
  {
   "title": "Used Sockets",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_vac_vbrlicense",
     "select": [
      [
       { "params": [ "usedSockets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "companyName", "operator": "=~", "value": "/^$tenant$/" },
      { "condition": "AND", "key": "backupServerName", "operator": "=~", "value": "/^$vbrserver$/" }
     ]
    }
   ]
  },
  {
   "title": "Used VMs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_vac_vbrlicense",
     "select": [
      [
       { "params": [ "usedVMs" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "companyName", "operator": "=~", "value": "/^$tenant$/" },
      { "condition": "AND", "key": "backupServerName", "operator": "=~", "value": "/^$vbrserver$/" }
     ]
    }
   ]
  },
  {
   "title": "$job - Last Result",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 13 },
   "repeat": "job",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "veeamjobname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_vac_jobs",
     "query": "SELECT last(\"uptime_latest\") FROM \"vsphere_host_sys\" WHERE (\"esxhostname\" =~ /^$esxi$/ AND \"vcenter\" =~ /^$vcenter$/ AND \"clustername\" =~ /^$clustername$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "veeamjobname", "operator": "=~", "value": "/^$job$/" }
     ]
    }
   ]
  }
 ]
}