{
 "title": "Grafana Dashboard for Veeam Availability Console - SP Overview",
 "description": "Grafana Dashboard for Veeam Availability Console - SP Overview",
 "tags": [
  "Veeam",
  "Veeam Availability Console",
  "VAC - SP Overview"
 ],
 "time": { "from": "now/d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "inter",
    "label": "Sampling",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "tenant",
    "label": "Tenant",
    "query": "SHOW TAG VALUES FROM veeam_vac_tenant WITH KEY=companyName"
   },
   {
    "name": "vbrserver",
    "label": "On-prem VBR",
    "query": "SHOW TAG VALUES FROM veeam_vac_vbrlicense WITH KEY=backupServerName"
   }
  ]
 },
 "panels": [
  { "title": "Service Provider Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 1 },
   "format": "dateTimeFromNow",
   "valueName": "name",
   "targets": [
    {
     "alias": "$tag_productName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "productName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_vac_vaclicense",
     "select": [
      [
       { "params": [ "licenseExpirationDate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "License Type",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "alias": "$tag_licenseType",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "licenseType" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_vac_vaclicense",
     "select": [
      [
       { "params": [ "licenseExpirationDate" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Expiration Date",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "format": "dateTimeFromNow",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_vac_vaclicense",
     "select": [
      [
       { "params": [ "licenseExpirationDate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*1000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Licenses Count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "format": "dateTimeFromNow",
   "valueName": "name",
   "targets": [
    {
     "alias": "$tag_licensesCount",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "licensesCount" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_vac_vaclicense",
     "select": [
      [
       { "params": [ "licenseExpirationDate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Support ID",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "alias": "$tag_supportID",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "supportID" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_vac_vaclicense",
     "select": [
      [
       { "params": [ "cloudconnectBackupServerCount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Service Provider",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 3, "y": 4 },
   "format": "dateTimeFromNow",
   "valueName": "name",
   "targets": [
    {
     "alias": "$tag_companyName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "companyName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_vac_vcclicense",
     "select": [
      [
       { "params": [ "licenseExpirationDate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Edition",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
   "format": "dateTimeFromNow",
   "valueName": "name",
   "targets": [
    {
     "alias": "$tag_edition",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "edition" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_vac_vcclicense",
     "select": [
      [
       { "params": [ "licenseExpirationDate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Licensed CC Backups",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_vac_vcclicense",
     "select": [
      [
       { "params": [ "licensedCloudConnectBackups" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Licensed CC Replicas",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_vac_vcclicense",
     "select": [
      [
       { "params": [ "licensedCloudConnectReplicas" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Licensed CC Servers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_vac_vcclicense",
     "select": [
      [
       { "params": [ "licensedCloudConnectServers" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Licensed CC Workstations",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_vac_vcclicense",
     "select": [
      [
       {
        "params": [
         "licensedCloudConnectWorkstations"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Contact Person",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 3, "y": 7 },
   "format": "dateTimeFromNow",
   "valueName": "name",
   "targets": [
    {
     "alias": "$tag_contactPerson",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "contactPerson" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_vac_vcclicense",
     "select": [
      [
       { "params": [ "licenseExpirationDate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "License Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 7 },
   "format": "dateTimeFromNow",
   "valueName": "name",
   "targets": [
    {
     "alias": "$tag_status",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "status" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_vac_vcclicense",
     "select": [
      [
       { "params": [ "licenseExpirationDate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Edition",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 7 },
   "format": "dateTimeFromNow",
   "valueName": "name",
   "targets": [
    {
     "alias": "$tag_type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_vac_vcclicense",
     "select": [
      [
       { "params": [ "licenseExpirationDate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Used CC Backups",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 7 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "alias": "$tag_type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_vac_vcclicense",
     "select": [
      [
       { "params": [ "usedCloudConnectBackups" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Used CC Replicas",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_vac_vcclicense",
     "select": [
      [
       { "params": [ "usedCloudConnectReplicas" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Used CC Servers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_vac_vcclicense",
     "select": [
      [
       { "params": [ "usedCloudConnectServers" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Used CC Workstations",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_vac_vcclicense",
     "select": [
      [
       { "params": [ "usedCloudConnectWorkstations" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$tenant Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "repeat": "tenant",
   "collapsed": true,
   "panels": [
    {
     "title": "Tenant Name",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 11 },
     "format": "none",
     "valueName": "name",
     "targets": [
      {
       "alias": "$tag_companyName",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "companyName" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "veeam_vac_tenant",
       "select": [
        [
         { "params": [ "expirationDate" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "companyName", "operator": "=~", "value": "/^$tenant$/" }
       ]
      }
     ]
    },
    {
     "title": "Expiration Date",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 3, "y": 11 },
     "format": "dateTimeFromNow",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "veeam_vac_tenant",
       "select": [
        [
         { "params": [ "expirationDate" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "*1000" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "companyName", "operator": "=~", "value": "/^$tenant$/" }
       ]
      }
     ]
    },
    {
     "title": "Storage Quota",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 9, "y": 11 },
     "format": "decmbytes",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "veeam_vac_backupresources",
       "select": [
        [
         { "params": [ "storageQuota" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "companyName", "operator": "=~", "value": "/^$tenant$/" }
       ]
      }
     ]
    },
    {
     "title": "VMs with Backup - Cloud",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 12, "y": 11 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "veeam_vac_tenant",
       "select": [
        [
         { "params": [ "vMsBackedUpToCloud" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "companyName", "operator": "=~", "value": "/^$tenant$/" }
       ]
      }
     ]
    },
    {
     "title": "Managed Physical Servers",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 15, "y": 11 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "veeam_vac_tenant",
       "select": [
        [
         { "params": [ "managedPhysicalServers" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "companyName", "operator": "=~", "value": "/^$tenant$/" }
       ]
      }
     ]
    },
    {
     "title": "Managed Cloud Servers",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 18, "y": 11 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "veeam_vac_tenant",
       "select": [
        [
         { "params": [ "managedCloudServers" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "companyName", "operator": "=~", "value": "/^$tenant$/" }
       ]
      }
     ]
    },
    {
     "title": "VMs with Backup",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 11 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "veeam_vac_tenant",
       "select": [
        [
         { "params": [ "vMsBackedUp" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "companyName", "operator": "=~", "value": "/^$tenant$/" }
       ]
      }
     ]
    },
    {
     "title": "Bandwidth",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 14 },
     "format": "MBs",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "veeam_vac_tenant",
       "query": "SELECT mean(\"allowedBandwidth\") FROM \"veeam_vac_tenant\" WHERE (\"companyName\" =~ /^$tenant$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "allowedBandwidth" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "companyName", "operator": "=~", "value": "/^$tenant$/" }
       ]
      }
     ]
    },
    {
     "title": "Max. Concurrent Tasks",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 6, "y": 14 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "veeam_vac_tenant",
       "select": [
        [
         { "params": [ "maxConcurrentTasks" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "companyName", "operator": "=~", "value": "/^$tenant$/" }
       ]
      }
     ]
    },
    {
     "title": "Traffic Quota",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 9, "y": 14 },
     "format": "decmbytes",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "veeam_vac_backupresources",
       "select": [
        [
         { "params": [ "trafficQuota" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "companyName", "operator": "=~", "value": "/^$tenant$/" }
       ]
      }
     ]
    },
    {
     "title": "WAN Acceleration",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 12, "y": 14 },
     "format": "none",
     "valueName": "name",
     "targets": [
      {
       "alias": "$tag_wanAccelerationEnabled",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "wanAccelerationEnabled" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "veeam_vac_backupresources",
       "select": [
        [
         { "params": [ "vMsQuota" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "companyName", "operator": "=~", "value": "/^$tenant$/" }
       ]
      }
     ]
    },
    {
     "title": "Managed Physical Workstations",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 15, "y": 14 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "veeam_vac_tenant",
       "select": [
        [
         { "params": [ "managedPhysicalWorkstations" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "companyName", "operator": "=~", "value": "/^$tenant$/" }
       ]
      }
     ]
    },
    {
     "title": "Managed Cloud Workstations",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 18, "y": 14 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "veeam_vac_tenant",
       "select": [
        [
         { "params": [ "managedCloudWorkstations" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "companyName", "operator": "=~", "value": "/^$tenant$/" }
       ]
      }
     ]
    },
    {
     "title": "VMs with Replica",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 14 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "veeam_vac_tenant",
       "select": [
        [
         { "params": [ "vMsReplicated" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "companyName", "operator": "=~", "value": "/^$tenant$/" }
       ]
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 6, "w": 5, "x": 0, "y": 17 },
     "content": "<img src=\"https://www.jorgedelacruz.es/wp-content/uploads/2019/01/onpremvbr-5.png\"></img>"
    },
    {
     "title": "Veeam Server Name",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 5, "x": 5, "y": 17 },
     "format": "none",
     "valueName": "name",
     "targets": [
      {
       "alias": "$tag_backupServerName",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "backupServerName" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "veeam_vac_vbrlicense",
       "select": [
        [
         { "params": [ "usedVMs" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "backupServerName", "operator": "=~", "value": "/^$vbrserver$/" },
        { "condition": "AND", "key": "companyName", "operator": "=~", "value": "/^$tenant$/" }
       ]
      }
     ]
    },
    {
     "title": "License Status",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 10, "y": 17 },
     "format": "none",
     "valueName": "name",
     "targets": [
      {
       "alias": "$tag_status",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "status" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "veeam_vac_vbrlicense",
       "select": [
        [
         { "params": [ "usedVMs" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "backupServerName", "operator": "=~", "value": "/^$vbrserver$/" },
        { "condition": "AND", "key": "companyName", "operator": "=~", "value": "/^$tenant$/" }
       ]
      }
     ]
    },
    {
     "title": "Support ID",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 14, "y": 17 },
     "format": "none",
     "valueName": "name",
     "targets": [
      {
       "alias": "$tag_SupportID",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "SupportID" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "veeam_vac_vbrlicense",
       "select": [
        [
         { "params": [ "usedVMs" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "backupServerName", "operator": "=~", "value": "/^$vbrserver$/" },
        { "condition": "AND", "key": "companyName", "operator": "=~", "value": "/^$tenant$/" }
       ]
      }
     ]
    },
    {
     "title": "Licensed Sockets",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 18, "y": 17 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "veeam_vac_vbrlicense",
       "select": [
        [
         { "params": [ "licensedSockets" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "companyName", "operator": "=~", "value": "/^$tenant$/" },
        { "condition": "AND", "key": "backupServerName", "operator": "=~", "value": "/^$vbrserver$/" }
       ]
      }
     ]
    },
    {
     "title": "Licensed VMs",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 17 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "veeam_vac_vbrlicense",
       "select": [
        [
         { "params": [ "licensedVMs" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "companyName", "operator": "=~", "value": "/^$tenant$/" },
        { "condition": "AND", "key": "backupServerName", "operator": "=~", "value": "/^$vbrserver$/" }
       ]
      }
     ]
    },
    {
     "title": "Edition",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 5, "x": 5, "y": 20 },
     "format": "none",
     "valueName": "name",
     "targets": [
      {
       "alias": "$tag_edition",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "edition" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "veeam_vac_vbrlicense",
       "select": [
        [
         { "params": [ "usedVMs" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "backupServerName", "operator": "=~", "value": "/^$vbrserver$/" },
        { "condition": "AND", "key": "companyName", "operator": "=~", "value": "/^$tenant$/" }
       ]
      }
     ]
    },
    {
     "title": "License Expiration Date",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 14, "y": 20 },
     "format": "dateTimeFromNow",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "veeam_vac_vbrlicense",
       "select": [
        [
         { "params": [ "licenseExpirationDate" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "*1000" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "companyName", "operator": "=~", "value": "/^$tenant$/" },
        { "condition": "AND", "key": "backupServerName", "operator": "=~", "value": "/^$vbrserver$/" }
       ]
      }
     ]
    },
    {
     "title": "Used Sockets",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 18, "y": 20 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "veeam_vac_vbrlicense",
       "select": [
        [
         { "params": [ "usedSockets" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "companyName", "operator": "=~", "value": "/^$tenant$/" },
        { "condition": "AND", "key": "backupServerName", "operator": "=~", "value": "/^$vbrserver$/" }
       ]
      }
     ]
    },
    {
     "title": "Used VMs",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 20 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "veeam_vac_vbrlicense",
       "select": [
        [
         { "params": [ "usedVMs" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "companyName", "operator": "=~", "value": "/^$tenant$/" },
        { "condition": "AND", "key": "backupServerName", "operator": "=~", "value": "/^$vbrserver$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}