{
 "title": "Veeam Overview",
 "description": "Grafana Dashboard for Veeam Availability Console - Job Overview",
 "tags": [
  "Veeam",
  "Veeam Availability Console",
  "VAC - Tenant Overview"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "inter",
    "label": "Sampling",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "tenant",
    "label": "Tenant",
    "query": "SHOW TAG VALUES FROM veeam_vac_tenant WITH KEY=companyName"
   },
   {
    "name": "vbrserver",
    "label": "On-prem VBR",
    "query": "SHOW TAG VALUES FROM veeam_vac_vbrlicense WITH KEY=backupServerName"
   },
   {
    "name": "job",
    "label": "Backup Job",
    "query": "SHOW TAG VALUES FROM veeam_vac_jobs WITH KEY=veeamjobname"
   }
  ]
 },
 "panels": [
  {
   "title": "Data last pulled from VSPC",
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "veeamjobname" ], "type": "tag" }
     ],
     "measurement": "veeam_vac_jobs",
     "query": "SELECT last(\"uptime_latest\") FROM \"vsphere_host_sys\" WHERE (\"esxhostname\" =~ /^$esxi$/ AND \"vcenter\" =~ /^$vcenter$/ AND \"clustername\" =~ /^$clustername$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "status" ], "type": "field" }
      ],
      [
       { "params": [ "lastRunTime" ], "type": "field" },
       { "params": [ " * 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "veeamjobname", "operator": "=~", "value": "/^$job$/" }
     ]
    }
   ]
  },
  {
   "title": "$job",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 2 },
   "repeat": "job",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "veeamjobname" ], "type": "tag" }
     ],
     "measurement": "veeam_vac_jobs",
     "query": "SELECT \"status\", \"lastRunTime\"  * 1000, \"transferredData\", \"protectedVMs\" FROM \"veeam_vac_jobs\" WHERE (\"veeamjobname\" =~ /^$job$/) AND $timeFilter GROUP BY \"veeamjobname\"",
     "select": [
      [
       { "params": [ "status" ], "type": "field" }
      ],
      [
       { "params": [ "lastRunTime" ], "type": "field" },
       { "params": [ " * 1000" ], "type": "math" }
      ],
      [
       { "params": [ "transferredData" ], "type": "field" }
      ],
      [
       { "params": [ "protectedVMs" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "veeamjobname", "operator": "=~", "value": "/^$job$/" }
     ]
    }
   ]
  },
  { "title": "Tenant Overview: $tenant ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Expiration Date",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_vac_tenant",
     "select": [
      [
       { "params": [ "expirationDate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "companyName", "operator": "=~", "value": "/^$tenant$/" }
     ]
    }
   ]
  },
  {
   "title": "Managed Physical Servers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_vac_tenant",
     "select": [
      [
       { "params": [ "managedPhysicalServers" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "companyName", "operator": "=~", "value": "/^$tenant$/" }
     ]
    }
   ]
  },
  {
   "title": "VMs with Backup",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_vac_tenant",
     "select": [
      [
       { "params": [ "vMsBackedUp" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "companyName", "operator": "=~", "value": "/^$tenant$/" }
     ]
    }
   ]
  },
  {
   "title": "VMs with Replica",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_vac_tenant",
     "select": [
      [
       { "params": [ "vMsReplicated" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "companyName", "operator": "=~", "value": "/^$tenant$/" }
     ]
    }
   ]
  },
  {
   "title": "Managed Physical Workstations",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_vac_tenant",
     "select": [
      [
       { "params": [ "managedPhysicalWorkstations" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "companyName", "operator": "=~", "value": "/^$tenant$/" }
     ]
    }
   ]
  },
  {
   "title": "Managed Cloud Servers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_vac_tenant",
     "select": [
      [
       { "params": [ "managedCloudServers" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "companyName", "operator": "=~", "value": "/^$tenant$/" }
     ]
    }
   ]
  },
  {
   "title": "VMs with Backup - Cloud",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_vac_tenant",
     "select": [
      [
       { "params": [ "vMsBackedUpToCloud" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "companyName", "operator": "=~", "value": "/^$tenant$/" }
     ]
    }
   ]
  },
  {
   "title": "Managed Cloud Workstations",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_vac_tenant",
     "select": [
      [
       { "params": [ "managedCloudWorkstations" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "companyName", "operator": "=~", "value": "/^$tenant$/" }
     ]
    }
   ]
  },
  {
   "title": "On-prem Repositories - Usage Capacity",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT ((\"capacity\") - (\"freeSpace\")) * (100 / (\"capacity\")), freeSpace FROM  \"veeam_vac_repositories\" WHERE (\"companyName\" =~ /^$tenant$/) AND $timeFilter GROUP BY \"companyName\",\"repoName\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Alternate View", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "$job",
   "type": "table",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "veeamjobname" ], "type": "tag" }
     ],
     "measurement": "veeam_vac_jobs",
     "query": "SELECT last(\"uptime_latest\") FROM \"vsphere_host_sys\" WHERE (\"esxhostname\" =~ /^$esxi$/ AND \"vcenter\" =~ /^$vcenter$/ AND \"clustername\" =~ /^$clustername$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "status" ], "type": "field" }
      ],
      [
       { "params": [ "lastRunTime" ], "type": "field" },
       { "params": [ " * 1000" ], "type": "math" }
      ],
      [
       { "params": [ "transferredData" ], "type": "field" }
      ],
      [
       { "params": [ "protectedVMs" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "veeamjobname", "operator": "=~", "value": "/^$job$/" }
     ]
    }
   ]
  }
 ]
}