{
 "title": "Veeam Historic - Repository",
 "description": "Grafana Dashboard for Veeam Availability Console - Repository History",
 "tags": [
  "Veeam",
  "Veeam Availability Console",
  "VAC - Tenant Overview"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "inter",
    "label": "Sampling",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "tenant",
    "label": "Tenant",
    "query": "SHOW TAG VALUES FROM veeam_vac_tenant WITH KEY=companyName"
   }
  ]
 },
 "panels": [
  {
   "title": "$tenant: Total Capacity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (\"capacity\") FROM  \"veeam_vac_repositories\" WHERE (\"companyName\" =~ /^$tenant$/) AND $timeFilter GROUP BY \"repoName\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$tenant: Used Capacity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT ((\"capacity\") - (\"freeSpace\")) FROM  \"veeam_vac_repositories\" WHERE (\"companyName\" =~ /^$tenant$/) AND $timeFilter GROUP BY \"repoName\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$tenant: Used Capacity %",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT ((\"capacity\") - (\"freeSpace\")) * (100 / (\"capacity\")) FROM  \"veeam_vac_repositories\" WHERE (\"companyName\" =~ /^$tenant$/) AND $timeFilter GROUP BY \"repoName\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "VMs with Backup",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "veeam_vac_tenant",
     "select": [
      [
       { "params": [ "vMsBackedUp" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "companyName", "operator": "=~", "value": "/^$tenant$/" }
     ]
    }
   ]
  },
  {
   "title": "Managed Physical Servers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "veeam_vac_tenant",
     "select": [
      [
       { "params": [ "managedPhysicalServers" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "companyName", "operator": "=~", "value": "/^$tenant$/" }
     ]
    }
   ]
  },
  {
   "title": "$tenant: On-prem Repositories - Usage Capacity %",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT ((\"capacity\") - (\"freeSpace\")) * (100 / (\"capacity\")),\"repoName\" FROM  \"veeam_vac_repositories\" WHERE (\"companyName\" =~ /^$tenant$/) AND $timeFilter GROUP BY \"repoName\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}