{
 "title": "Grafana Dashboard for Veeam Backup for Azure",
 "description": "Grafana Dashboard for Veeam Backup for Azure v3 -  (Grafana 8.x / InfluxDB v2.x)",
 "tags": [
  "veeam",
  "azure",
  "veeam azure",
  "vba"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "PolicyName",
    "label": "Policy Name",
    "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_azure_sessions\")\r\n  |> keep(columns: [\"sessionPolicyName\"])\r\n  |> distinct(column: \"sessionPolicyName\")\r\n  |> group()"
   },
   {
    "name": "VMName",
    "label": "Unprotected VM",
    "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_azure_vm_unprotected\")\r\n  |> filter(fn: (r) => r[\"VMName\"] != \"\")\r\n  |> keep(columns: [\"VMName\"])\r\n  |> distinct(column: \"VMName\")\r\n  |> group()"
   },
   {
    "name": "Repository",
    "label": "Blob Repository",
    "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_azure_repositories\")\r\n  |> filter(fn: (r) => r[\"repoName\"] != \"\")\r\n  |> keep(columns: [\"repoName\"])\r\n  |> distinct(column: \"repoName\")\r\n  |> group()"
   },
   {
    "name": "PolicyType",
    "label": "Policy Type",
    "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_azure_sessions\")\r\n  |> filter(fn: (r) => r[\"sessionType\"] != \"\")\r\n  |> keep(columns: [\"sessionType\"])\r\n  |> distinct(column: \"sessionType\")\r\n  |> group()"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 0, "y": 0 },
   "options": {
    "content": "<a href=\"https://www.veeam.com/backup-azure.html\" target=\"_blank\"><img src=\"https://www.jorgedelacruz.es/VCB_product_icon.svg\" alt=\"drawing\" width=\"50\"/></a>\n\n"
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 15, "x": 1, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Total Policies",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_azure_overview",
     "query": "  from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_azure_overview\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Policies\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "Policies" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Total Repositories",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_azure_overview",
     "query": "  from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_azure_overview\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Repositories\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "Repositories" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Total Instances",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_azure_overview",
     "query": "  from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_azure_overview\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"VMs\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "VMs" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Total Protected VMs",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_azure_overview",
     "query": "  from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_azure_overview\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"VMsProtected\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "VMsProtected" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Version $tag_version",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "version" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "veeam_azure_overview",
     "query": "  from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_azure_overview\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Policies\")\r\n  |> group(columns: [\"version\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n",
     "select": [
      [
       { "params": [ "Policies" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Worker $tag_workerversion",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "workerversion" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "veeam_azure_overview",
     "query": "  from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_azure_overview\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Policies\")\r\n  |> group(columns: [\"workerversion\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)",
     "select": [
      [
       { "params": [ "Policies" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Unprotected VMs",
   "type": "geomap",
   "description": "On this Map, you can quickly know which VMs are not Protected by Veeam Backup for Azure. \nWith a simple, yet powerful view, you can understand and try to mitigate the red spots.",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "alias": "$tag_geohash",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "geohash" ], "type": "tag" },
      { "params": [ "VMRegion" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "veeam_azure_vm_unprotected",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_aws_vm_unprotected\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"UPVM\" and r._value >=1)\r\n  |> group(columns: [\"geohash\",\"VMRegion\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "UPVM" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "metric" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Protected VMs Overview",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Protected VMs",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "veeam_azure_vm_protected",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_azure_vm_protected\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"TotalVMs\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n",
     "select": [
      [
       { "params": [ "TotalVMs" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Unprotected VMs",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "veeam_azure_vm_unprotected",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_azure_vm_unprotected\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"TotalVMs\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "TotalVMs" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Job Duration",
   "type": "timeseries",
   "description": "On this Panel, you can quickly know how much time did a Backup, or Snapshot Policy take. You can quickly filter by Policy Name on the top menu.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "$tag_sessionPolicyName - $tag_sessionType",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sessionPolicyName" ], "type": "tag" },
      { "params": [ "sessionType" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "veeam_azure_sessions",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_azure_sessions\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"sessionDuration\")\r\n  |> filter(fn: (r) => r[\"sessionType\"] =~ /${PolicyType:regex}/)\r\n  |> filter(fn: (r) => r[\"sessionPolicyName\"] =~ /${PolicyName:regex}/)\r\n  |> group(columns: [\"sessionPolicyName\",\"sessionType\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n\r\n",
     "select": [
      [
       { "params": [ "sessionDuration" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sessionType", "operator": "=~", "value": "/^$PolicyType$/" },
      { "condition": "AND", "key": "sessionPolicyName", "operator": "=~", "value": "/^$PolicyName$/" }
     ]
    }
   ]
  },
  {
   "title": "Job Historical Information",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "alias": "$tag_sessionPolicyName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sessionPolicyName" ], "type": "tag" },
      { "params": [ "sessionType" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "veeam_azure_sessions",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_azure_sessions\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"sessionStatus\")\r\n  |> filter(fn: (r) => r[\"sessionPolicyName\"] =~ /${PolicyName:regex}/)\r\n  |> group(columns: [\"sessionPolicyName\",\"sessionType\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n",
     "select": [
      [
       { "params": [ "sessionStatus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sessionPolicyName", "operator": "=~", "value": "/^$PolicyName$/" }
     ]
    }
   ]
  },
  {
   "title": "Protected Databases",
   "type": "table",
   "description": "On this Panel, you can quickly know which Databases are Protected by Veeam Backup for Azure. With all the needed details as DB Name, SQL Name, Azure Region, and Azure Instance Type.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "VMName" ], "type": "tag" },
      { "params": [ "VMRegion" ], "type": "tag" },
      { "params": [ "VMType" ], "type": "tag" },
      { "params": [ "VMOSType" ], "type": "tag" },
      { "params": [ "VMprivateIP" ], "type": "tag" }
     ],
     "measurement": "veeam_azure_vm",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_azure_vm_database\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"DatabaseSize\")\r\n  |> group(columns: [\"DatabaseName\"])\r\n  |> last()\r\n  ",
     "select": [
      [
       { "params": [ "VMSize" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "VM  Size" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Protected VMs",
   "type": "table",
   "description": "On this Panel, you can quickly know which VMs are Protected by Veeam Backup for Azure. With all the needed details as VM Name, Operating System, Azure Region, and Azure Instance Type.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 18 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "VMName" ], "type": "tag" },
      { "params": [ "VMRegion" ], "type": "tag" },
      { "params": [ "VMType" ], "type": "tag" },
      { "params": [ "VMOSType" ], "type": "tag" },
      { "params": [ "VMprivateIP" ], "type": "tag" }
     ],
     "measurement": "veeam_azure_vm",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_azure_vm\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"VMSize\")\r\n  |> group(columns: [\"VMName\",\"VMRegion\",\"VMType\",\"VMOSType\",\"VMprivateIP\"])\r\n  |> last()\r\n  ",
     "select": [
      [
       { "params": [ "VMSize" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "VM  Size" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Unprotected VMs",
   "type": "table",
   "description": "On this Panel, you can quickly know which VMs are not Protected by Veeam Backup for Azure. With all the needed details as VM Name, Operating System, Azure Region, and Azure Instance Type.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "VMName" ], "type": "tag" },
      { "params": [ "VMRegion" ], "type": "tag" },
      { "params": [ "VMType" ], "type": "tag" },
      { "params": [ "VMOSType" ], "type": "tag" },
      { "params": [ "VMprivateIP" ], "type": "tag" }
     ],
     "measurement": "veeam_azure_vm_unprotected",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_azure_vm_unprotected\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"VMSize\")\r\n  |> filter(fn: (r) => r[\"VMName\"] =~ /${VMName:regex}/)\r\n  |> group(columns: [\"VMName\",\"VMRegion\",\"VMType\",\"VMOSType\", \"VMprivateIP\"])\r\n  |> last()",
     "select": [
      [
       { "params": [ "VMSize" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "VM  Size" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "VMName", "operator": "=~", "value": "/^$VMName$/" }
     ]
    }
   ]
  },
  {
   "title": "Backup Repositories",
   "type": "table",
   "description": "On this Panel, you can quickly see all your Backup Repositories, with name, type, etc.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "repoAccountName" ], "type": "tag" },
      { "params": [ "repoContainer" ], "type": "tag" },
      { "params": [ "repoDescription" ], "type": "tag" },
      { "params": [ "repoName" ], "type": "tag" },
      { "params": [ "RepositoryTier" ], "type": "tag" }
     ],
     "measurement": "veeam_azure_repositories",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_azure_repositories\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"repoEncryption\")\r\n  |> group(columns: [\"repoAccountName\",\"repoContainer\",\"repoDescription\",\"repoName\",\"RepositoryTier\"])\r\n  |> last()",
     "select": [
      [
       { "params": [ "repoEncryption" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Encryption" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "repoName", "operator": "=~", "value": "/^$Repository$/" }
     ]
    }
   ]
  },
  {
   "title": "Protection Policies",
   "type": "table",
   "description": "On this Panel, you can quickly see your different Policies, the retention, if it has application-aware enabled, etc.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "PolicyName" ], "type": "tag" },
      { "params": [ "PolicyStatus" ], "type": "tag" }
     ],
     "measurement": "veeam_azure_policies",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_azure_policies\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"PolicyAppAware\" or r[\"_field\"] == \"PolicySnapshotCountDaily\" or r[\"_field\"] == \"PolicySnapshotCountWeekly\" or r[\"_field\"] == \"PolicySnapshotCountMonthly\" )\r\n  |> filter(fn: (r) => r[\"PolicyName\"] =~ /${PolicyName:regex}/)\r\n  |> pivot(rowKey:[\"_time\"], columnKey:[\"_field\"], valueColumn:\"_value\")\r\n  |> group(columns: [\"PolicyName\",\"_field\"])",
     "select": [
      [
       { "params": [ "PolicyAppAware" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Application-Aware" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "PolicyName", "operator": "=~", "value": "/^$PolicyName$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 31 },
   "options": {
    "content": "<a href=\"https://www.jorgedelacruz.es\"><img src=\"https://www.jorgedelacruz.es/wp-content/uploads/2019/04/jorgedelacruz-banner_2efede4ef704c939e63a3763231f5961.png\"></a>\n\n\n\n"
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}