{
 "title": "Grafana Dashboard for Veeam Backup for Salesforce",
 "description": "Grafana Dashboard for Veeam Backup for Salesforce v1 -  (Grafana 8.x / InfluxDB v2.x)",
 "tags": [
  "veeam",
  "vbsf",
  "veeam salesforce",
  "salesforce"
 ],
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Organization",
    "label": "Organization",
    "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_salesforce_organizations\")\r\n  |> keep(columns: [\"organizationCompanyName\"])\r\n  |> distinct(column: \"organizationCompanyName\")\r\n  |> group()"
   },
   {
    "name": "Company",
    "label": "Company",
    "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_salesforce_companies\")\r\n  |> filter(fn: (r) => r[\"companyName\"] != \"\")\r\n  |> filter(fn: (r) => r[\"companyName\"] =~ /${Company:regex}/)\r\n  |> keep(columns: [\"companyName\"])\r\n  |> distinct(column: \"companyName\")\r\n  |> group()"
   },
   {
    "name": "Databases",
    "label": "Databases",
    "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_salesforce_databases\")\r\n  |> filter(fn: (r) => r[\"databaseName\"] != \"\")\r\n  |> filter(fn: (r) => r[\"companyName\"] =~ /${Company:regex}/)\r\n  |> keep(columns: [\"databaseName\"])\r\n  |> distinct(column: \"databaseName\")\r\n  |> group()"
   },
   {
    "name": "JobName",
    "label": "Job Name",
    "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_salesforce_jobs\")\r\n  |> filter(fn: (r) => r[\"jobName\"] != \"\")\r\n  |> filter(fn: (r) => r[\"companyName\"] =~ /${Company:regex}/)\r\n  |> keep(columns: [\"jobName\"])\r\n  |> distinct(column: \"jobName\")\r\n  |> group()"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 0, "y": 0 },
   "options": {
    "content": "<a href=\"https://www.veeam.com/backup-salesforce.html?ad=menu-products\" target=\"_blank\"><img src=\"https://www.jorgedelacruz.es/VCB_product_icon.svg\" alt=\"drawing\" width=\"50\"/></a>\n\n"
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 1, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Total Policies",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_azure_overview",
     "query": "from(bucket: \"veeam\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_salesforce_jobs\")\n  |> filter(fn: (r) => r[\"companyName\"] =~ /${Company:regex}/)\n  |> keep(columns: [\"jobName\"])\n  |> distinct(column: \"jobName\")\n  |> group()\n  |> count()\n",
     "select": [
      [
       { "params": [ "Policies" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Total Repositories",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_azure_overview",
     "query": "from(bucket: \"veeam\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_salesforce_databases\")\r\n  |> keep(columns: [\"databaseID\"])\r\n  |> distinct(column: \"databaseID\")\r\n  |> group()\r\n  |> count()",
     "select": [
      [
       { "params": [ "Repositories" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Total Instances",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_azure_overview",
     "query": "from(bucket: \"veeam\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_salesforce_organizations\")\r\n  |> keep(columns: [\"organizationSFID\"])\r\n  |> distinct(column: \"organizationSFID\")\r\n  |> group()\r\n  |> count()",
     "select": [
      [
       { "params": [ "VMs" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Total Protected VMs",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_azure_overview",
     "query": "from(bucket: \"veeam\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_salesforce_companies\")\r\n  |> keep(columns: [\"companyID\"])\r\n  |> distinct(column: \"companyID\")\r\n  |> group()\r\n  |> count()",
     "select": [
      [
       { "params": [ "VMsProtected" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Version $tag_version",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "version" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "veeam_azure_overview",
     "query": "from(bucket: \"veeam\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_salesforce_overview\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"VBSF\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n",
     "select": [
      [
       { "params": [ "Policies" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Total Policies",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_azure_overview",
     "query": "from(bucket: \"veeam\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_salesforce_jobslogs\")\n  |> filter(fn: (r) => r[\"_field\"] == \"jobAPICalls\")\n  |> group(columns: [\"_field\"])\n  |> sum()\n  |> group()",
     "select": [
      [
       { "params": [ "Policies" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Total Repositories",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_azure_overview",
     "query": "from(bucket: \"veeam\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_salesforce_restores\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"restoreAPICalls\")\r\n  |> group(columns: [\"_field\"])\r\n  |> sum()\r\n  |> group()",
     "select": [
      [
       { "params": [ "Repositories" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Job Historical Information",
   "type": "table",
   "gridPos": { "h": 14, "w": 10, "x": 0, "y": 2 },
   "targets": [
    {
     "alias": "$tag_sessionPolicyName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sessionPolicyName" ], "type": "tag" },
      { "params": [ "sessionType" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "veeam_azure_sessions",
     "query": "from(bucket: \"veeam\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_salesforce_jobs\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"jobLastRunUnix\")\r\n  |> filter(fn: (r) => r[\"companyName\"] =~ /${Company:regex}/)\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({ r with  _value: float(v: r.jobLastRunUnix) * 1000.0 }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n",
     "select": [
      [
       { "params": [ "sessionStatus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sessionPolicyName", "operator": "=~", "value": "/^$PolicyName$/" }
     ]
    }
   ]
  },
  {
   "title": "Policy Duration",
   "type": "timeseries",
   "description": "On this Panel, you can quickly know how much time did a Backup Policy take. You can quickly filter by Policy Name on the top menu.",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "$tag_sessionPolicyName - $tag_sessionType",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sessionPolicyName" ], "type": "tag" },
      { "params": [ "sessionType" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "veeam_azure_sessions",
     "query": "from(bucket: \"veeam\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_salesforce_jobslogs\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"jobDuration\")\r\n  |> filter(fn: (r) => r[\"companyName\"] =~ /${Company:regex}/)\r\n  |> filter(fn: (r) => r[\"jobName\"] =~ /${JobName:regex}/)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n",
     "select": [
      [
       { "params": [ "sessionDuration" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sessionType", "operator": "=~", "value": "/^$PolicyType$/" },
      { "condition": "AND", "key": "sessionPolicyName", "operator": "=~", "value": "/^$PolicyName$/" }
     ]
    }
   ]
  },
  {
   "title": "API Consumption",
   "type": "timeseries",
   "description": "On this Panel, you can quickly know how many API Calls per Job chunk. You can quickly filter by Policy Name on the top menu.",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "alias": "$tag_sessionPolicyName - $tag_sessionType",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sessionPolicyName" ], "type": "tag" },
      { "params": [ "sessionType" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "veeam_azure_sessions",
     "query": "from(bucket: \"veeam\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_salesforce_jobslogs\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"jobAPICalls\")\r\n  |> filter(fn: (r) => r[\"companyName\"] =~ /${Company:regex}/)\r\n  |> filter(fn: (r) => r[\"jobName\"] =~ /${JobName:regex}/)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n",
     "select": [
      [
       { "params": [ "sessionDuration" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sessionType", "operator": "=~", "value": "/^$PolicyType$/" },
      { "condition": "AND", "key": "sessionPolicyName", "operator": "=~", "value": "/^$PolicyName$/" }
     ]
    }
   ]
  },
  {
   "title": "Detailed Job Historical Information",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "alias": "$tag_sessionPolicyName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sessionPolicyName" ], "type": "tag" },
      { "params": [ "sessionType" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "veeam_azure_sessions",
     "query": "from(bucket: \"veeam\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_salesforce_jobslogs\")\r\n  |> filter(fn: (r) => r[\"companyName\"] =~ /${Company:regex}/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"jobAPICalls\" or r[\"_field\"] == \"jobDuration\" or r[\"_field\"] == \"jobProccessedObjects\" or r[\"_field\"] == \"jobRowsDeleted\" or r[\"_field\"] == \"jobRowsFailed\" or r[\"_field\"] == \"jobRowsInserted\" or r[\"_field\"] == \"jobRowsLoaded\" or r[\"_field\"] == \"jobRowsUpdated\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n",
     "select": [
      [
       { "params": [ "sessionStatus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sessionPolicyName", "operator": "=~", "value": "/^$PolicyName$/" }
     ]
    },
    {
     "alias": "$tag_sessionPolicyName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sessionPolicyName" ], "type": "tag" },
      { "params": [ "sessionType" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "veeam_azure_sessions",
     "query": "from(bucket: \"veeam\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_salesforce_jobslogs\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"jobLastRunUnix\")\r\n  |> filter(fn: (r) => r[\"companyName\"] =~ /${Company:regex}/)\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({ r with  _value: float(v: r.jobLastRunUnix) * 1000.0 }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n",
     "select": [
      [
       { "params": [ "sessionStatus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sessionPolicyName", "operator": "=~", "value": "/^$PolicyName$/" }
     ]
    }
   ]
  },
  {
   "title": "Restores Historical Information",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "alias": "$tag_sessionPolicyName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sessionPolicyName" ], "type": "tag" },
      { "params": [ "sessionType" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "veeam_azure_sessions",
     "query": "from(bucket: \"veeam\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_salesforce_restores\")\r\n  |> filter(fn: (r) => r[\"companyName\"] =~ /${Company:regex}/)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n",
     "select": [
      [
       { "params": [ "sessionStatus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sessionPolicyName", "operator": "=~", "value": "/^$PolicyName$/" }
     ]
    }
   ]
  },
  {
   "title": "Salesforce Organizations",
   "type": "table",
   "description": "On this Panel, you can quickly see your different Organizations, Databases, etc.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "PolicyName" ], "type": "tag" },
      { "params": [ "PolicyStatus" ], "type": "tag" }
     ],
     "measurement": "veeam_azure_policies",
     "query": "from(bucket: \"veeam\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_salesforce_organizations\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"organizationDBID\")\r\n  |> last()",
     "select": [
      [
       { "params": [ "PolicyAppAware" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Application-Aware" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "PolicyName", "operator": "=~", "value": "/^$PolicyName$/" }
     ]
    }
   ]
  },
  {
   "title": "Companies",
   "type": "table",
   "description": "On this Panel, you can quickly see all your Databases, with name, type, etc.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "repoAccountName" ], "type": "tag" },
      { "params": [ "repoContainer" ], "type": "tag" },
      { "params": [ "repoDescription" ], "type": "tag" },
      { "params": [ "repoName" ], "type": "tag" },
      { "params": [ "RepositoryTier" ], "type": "tag" }
     ],
     "measurement": "veeam_azure_repositories",
     "query": "from(bucket: \"veeam\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_salesforce_companies\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> last()",
     "select": [
      [
       { "params": [ "repoEncryption" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Encryption" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "repoName", "operator": "=~", "value": "/^$Repository$/" }
     ]
    }
   ]
  },
  {
   "title": "Databases",
   "type": "table",
   "description": "On this Panel, you can quickly know which VMs are Protected by Veeam Backup for Azure. With all the needed details as VM Name, Operating System, Azure Region, and Azure Instance Type.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "VMName" ], "type": "tag" },
      { "params": [ "VMRegion" ], "type": "tag" },
      { "params": [ "VMType" ], "type": "tag" },
      { "params": [ "VMOSType" ], "type": "tag" },
      { "params": [ "VMprivateIP" ], "type": "tag" }
     ],
     "measurement": "veeam_azure_vm",
     "query": "from(bucket: \"veeam\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_salesforce_databases\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> last()\r\n  ",
     "select": [
      [
       { "params": [ "VMSize" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "VM  Size" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 49 },
   "options": {
    "content": "<a href=\"https://www.jorgedelacruz.es\"><img src=\"https://www.jorgedelacruz.es/wp-content/uploads/2019/04/jorgedelacruz-banner_2efede4ef704c939e63a3763231f5961.png\"></a>\n\n\n\n"
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}