{
 "title": "Grafana Dashboard for Veeam Backup for Microsoft Office 365 v3.0",
 "description": "Grafana Dashboard for Veeam Backup for Microsoft Office 365 Dashboard",
 "tags": [
  "Veeam",
  "Office 365"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "inter",
    "label": "Sampling",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "organization",
    "label": "Organization",
    "query": "SHOW TAG VALUES FROM veeam_office365_organization WITH KEY=veeamOrgName"
   },
   {
    "name": "job",
    "label": "Backup Job",
    "query": "SHOW TAG VALUES FROM veeam_office365_jobs WITH KEY=veeamjobname"
   },
   {
    "name": "proxies",
    "label": "Backup Proxies",
    "query": "SHOW TAG VALUES FROM veeam_office365_proxies WITH KEY=proxies"
   },
   {
    "name": "repository",
    "label": "Backup Repository",
    "query": "SHOW TAG VALUES FROM veeam_office365_repository WITH KEY=repository"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "content": "![Veeam Backup for Microsoft Office 365 - Dashboard](https://upload.wikimedia.org/wikipedia/commons/7/74/Office_365_logo.png)"
  },
  {
   "title": "Licensed Users",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_organization",
     "query": "SELECT last(\"uptime_latest\") FROM \"vsphere_host_sys\" WHERE (\"esxhostname\" =~ /^$esxi$/ AND \"vcenter\" =~ /^$vcenter$/ AND \"clustername\" =~ /^$clustername$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "licensedUsers" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "veeamOrgName", "operator": "=~", "value": "/^$organization$/" }
     ]
    }
   ]
  },
  {
   "title": "New Users",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_organization",
     "query": "SELECT last(\"uptime_latest\") FROM \"vsphere_host_sys\" WHERE (\"esxhostname\" =~ /^$esxi$/ AND \"vcenter\" =~ /^$vcenter$/ AND \"clustername\" =~ /^$clustername$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "newUsers" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "veeamOrgName", "operator": "=~", "value": "/^$organization$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Threads Numbers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "veeam_office365_proxies",
     "query": "SELECT sum(\"threadsNumber\") FROM \"veeam_office365_proxies\" WHERE (\"proxies\" =~ /^$proxies$/) AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "threadsNumber" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "proxies", "operator": "=~", "value": "/^$proxies$/" }
     ]
    }
   ]
  },
  {
   "title": "Change Rate",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "format": "decbytes",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "veeam_office365_jobs",
     "query": "SELECT last(\"uptime_latest\") FROM \"vsphere_host_sys\" WHERE (\"esxhostname\" =~ /^$esxi$/ AND \"vcenter\" =~ /^$vcenter$/ AND \"clustername\" =~ /^$clustername$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "transferredData" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "veeamjobname", "operator": "=~", "value": "/^$job$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Objects Processed",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_jobs",
     "query": "SELECT last(\"uptime_latest\") FROM \"vsphere_host_sys\" WHERE (\"esxhostname\" =~ /^$esxi$/ AND \"vcenter\" =~ /^$vcenter$/ AND \"clustername\" =~ /^$clustername$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "processedObjects" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "veeamjobname", "operator": "=~", "value": "/^$job$/" }
     ]
    }
   ]
  },
  { "title": "Summaries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "$job - Last Result",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 6 },
   "repeat": "job",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "veeamjobname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_jobs",
     "query": "SELECT last(\"uptime_latest\") FROM \"vsphere_host_sys\" WHERE (\"esxhostname\" =~ /^$esxi$/ AND \"vcenter\" =~ /^$vcenter$/ AND \"clustername\" =~ /^$clustername$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "veeamjobname", "operator": "=~", "value": "/^$job$/" }
     ]
    }
   ]
  },
  {
   "title": "$job - Restore - Items Processed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 9 },
   "repeat": "job",
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "veeamjobname" ], "type": "tag" }
     ],
     "measurement": "veeam_office365_restoresession",
     "query": "SELECT last(\"uptime_latest\") FROM \"vsphere_host_sys\" WHERE (\"esxhostname\" =~ /^$esxi$/ AND \"vcenter\" =~ /^$vcenter$/ AND \"clustername\" =~ /^$clustername$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "itemsProcessed" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "veeamjobname", "operator": "=~", "value": "/^$job$/" }
     ]
    }
   ]
  },
  {
   "title": "$job - Restore - Items Recovered",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 12 },
   "repeat": "job",
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "veeamjobname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_restoresession",
     "query": "SELECT last(\"uptime_latest\") FROM \"vsphere_host_sys\" WHERE (\"esxhostname\" =~ /^$esxi$/ AND \"vcenter\" =~ /^$vcenter$/ AND \"clustername\" =~ /^$clustername$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "itemsSuccess" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "veeamjobname", "operator": "=~", "value": "/^$job$/" }
     ]
    }
   ]
  },
  { "title": "Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Job Read/Write Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "Bps", "label": "Read MB/s" }
   ],
   "targets": [
    {
     "alias": "$tag_veeamjobname - read",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "veeamjobname" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_jobs",
     "query": "SELECT mean(\"usage_average\") FROM \"vsphere_host_cpu\" WHERE \"esxhostname\" = ($esxi) AND $timeFilter GROUP BY time($__interval), \"host\" fill(none)",
     "select": [
      [
       { "params": [ "readRate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "veeamjobname", "operator": "=~", "value": "/^$job$/" }
     ]
    },
    {
     "alias": "$tag_veeamjobname - write",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "veeamjobname" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_jobs",
     "query": "SELECT mean(\"usage_average\") FROM \"vsphere_host_cpu\" WHERE \"esxhostname\" = ($esxi) AND $timeFilter GROUP BY time($__interval), \"host\" fill(none)",
     "select": [
      [
       { "params": [ "writeRate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "veeamjobname", "operator": "=~", "value": "/^$job$/" }
     ]
    }
   ]
  },
  {
   "title": "Job Processing Rate/Transferred Data",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "KBs", "label": "Processed KB/s" }
   ],
   "targets": [
    {
     "alias": "$tag_veeamjobname - processed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "veeamjobname" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_jobs",
     "query": "SELECT mean(\"usage_average\") FROM \"vsphere_host_cpu\" WHERE \"esxhostname\" = ($esxi) AND $timeFilter GROUP BY time($__interval), \"host\" fill(none)",
     "select": [
      [
       { "params": [ "processingRate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "veeamjobname", "operator": "=~", "value": "/^$job$/" }
     ]
    },
    {
     "alias": "$tag_veeamjobname - transferred",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "veeamjobname" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_jobs",
     "query": "SELECT mean(\"usage_average\") FROM \"vsphere_host_cpu\" WHERE \"esxhostname\" = ($esxi) AND $timeFilter GROUP BY time($__interval), \"host\" fill(none)",
     "select": [
      [
       { "params": [ "transferredData" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "veeamjobname", "operator": "=~", "value": "/^$job$/" }
     ]
    }
   ]
  },
  {
   "title": "Job Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "s", "label": "Duration in Seconds" }
   ],
   "targets": [
    {
     "alias": "$tag_veeamjobname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "veeamjobname" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_jobs",
     "query": "SELECT mean(\"usage_average\") FROM \"vsphere_host_cpu\" WHERE \"esxhostname\" = ($esxi) AND $timeFilter GROUP BY time($__interval), \"host\" fill(none)",
     "select": [
      [
       { "params": [ "totalDuration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "veeamjobname", "operator": "=~", "value": "/^$job$/" }
     ]
    }
   ]
  },
  {
   "title": "Job Historical Information",
   "type": "table",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 23 },
   "targets": [
    {
     "alias": "$tag_veeamjobname",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "veeamjobname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_jobs",
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "veeamjobname", "operator": "=~", "value": "/^$job$/" }
     ]
    }
   ]
  },
  {
   "title": "Datastores - Usage Capacity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 23 },
   "yaxes": [
    { "format": "decbytes", "label": "Used Space GB" }
   ],
   "targets": [
    {
     "alias": "$tag_repository",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "source" ], "type": "tag" }
     ],
     "measurement": "vsphere_datastore_disk",
     "query": "SELECT  (mean(\"capacity\") - mean(\"freeSpace\"))  FROM  \"veeam_office365_repository\" WHERE (\"repository\" =~ /^$repository$/) AND $timeFilter GROUP BY time(5m), \"repository\"",
     "select": [
      [
       { "params": [ "capacity_latest" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$datastore$/" }
     ]
    }
   ]
  },
  { "title": "Backup Repositories Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "$repository",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 32 },
   "repeat": "repository",
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_repository",
     "query": "SELECT  (mean(\"capacity\") - mean(\"freeSpace\")) * (100 / mean(\"capacity\"))  FROM  \"veeam_office365_repository\" WHERE (\"repository\" =~ /^$repository$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "capacity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "repository", "operator": "=~", "value": "/^$repository$/" }
     ]
    }
   ]
  }
 ]
}