{
 "title": "Grafana Dashboard for Veeam Backup for Microsoft 365",
 "description": "Grafana Dashboard for Veeam Backup for Microsoft 365 Dashboard / VBO v6 + Influx v2",
 "tags": [
  "Veeam",
  "veeam microsoft 365 audit",
  "veeam microsoft 365"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "inter",
    "label": "Sampling",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "version",
    "label": "Veeam Office 365 Version",
    "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_office365_version\")\r\n  |> keep(columns: [\"veeamVersion\"])\r\n  |> distinct(column: \"veeamVersion\")\r\n  |> group()\r\n"
   },
   {
    "name": "organization",
    "label": "Organization",
    "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_office365_organization\")\r\n  |> keep(columns: [\"veeamOrgName\"])\r\n  |> distinct(column: \"veeamOrgName\")\r\n  |> group()"
   },
   {
    "name": "job",
    "label": "Backup Job",
    "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_office365_jobs\")\r\n  |> keep(columns: [\"veeamjobname\"])\r\n  |> distinct(column: \"veeamjobname\")\r\n  |> group()"
   },
   {
    "name": "proxies",
    "label": "Backup Proxies",
    "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_office365_proxies\")\r\n  |> keep(columns: [\"proxies\"])\r\n  |> distinct(column: \"proxies\")\r\n  |> group()"
   },
   {
    "name": "objectstorage",
    "label": "Object Storage",
    "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_office365_objectstorage\")\r\n  |> keep(columns: [\"objectname\"])\r\n  |> distinct(column: \"objectname\")\r\n  |> group()\r\n"
   },
   {
    "name": "repository",
    "label": "Backup Repository",
    "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_office365_repository\")\r\n  |> keep(columns: [\"repository\"])\r\n  |> distinct(column: \"repository\")\r\n  |> group()"
   },
   {
    "name": "rbacrole",
    "label": "RBAC Role",
    "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_office365_rbac_roles\")\r\n  |> filter(fn: (r) => r[\"organization\"] =~ /${organization:regex}/)\r\n  |> keep(columns: [\"rbacRoleName\"])\r\n  |> distinct(column: \"rbacRoleName\")\r\n  |> group()\r\n"
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "options": {
    "content": "<span style=\"color:#fff; font-family: 'Lato'; font-size: 2.1em;\">Veeam Backup for Microsoft 365</span><br/>\r\n<span style=\"color:#fff; font-family: 'Lato'; font-size: 2em;\">Installed version: $version</span>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Licensed Users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_organization",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_office365_organization\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"licensedUsers\")\r\n  |> filter(fn: (r) => r[\"veeamOrgName\"] =~ /${organization:regex}/)\r\n  |> group(columns: [\"licensedUsers\",\"_field\"])\r\n  |> aggregateWindow(every: ${inter}, fn: sum, createEmpty: false)",
     "select": [
      [
       { "params": [ "licensedUsers" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "veeamOrgName", "operator": "=~", "value": "/^$organization$/" }
     ]
    }
   ]
  },
  {
   "title": "New Users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_organization",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_office365_organization\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"newUsers\")\r\n  |> filter(fn: (r) => r[\"veeamOrgName\"] =~ /${organization:regex}/)\r\n  |> group(columns: [\"newUsers\",\"_field\"])\r\n  |> aggregateWindow(every: ${inter}, fn: sum, createEmpty: false)",
     "select": [
      [
       { "params": [ "newUsers" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "veeamOrgName", "operator": "=~", "value": "/^$organization$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Threads Numbers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "veeam_office365_proxies",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_office365_proxies\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"threadsNumber\")\r\n  |> filter(fn: (r) => r[\"proxies\"] =~ /${proxies:regex}/)\r\n  |> group(columns: [\"threadsNumber\",\"_field\"])\r\n  |> aggregateWindow(every: ${inter}, fn: last, createEmpty: false)",
     "select": [
      [
       { "params": [ "threadsNumber" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "proxies", "operator": "=~", "value": "/^$proxies$/" }
     ]
    }
   ]
  },
  {
   "title": "Change Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "veeam_office365_jobs",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_office365_jobs\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"transferredData\")\r\n  |> filter(fn: (r) => r[\"veeamjobname\"] =~ /${job:regex}/)\r\n  |> group(columns: [\"transferredData\",\"_field\"])\r\n  |> aggregateWindow(every: ${inter}, fn: sum, createEmpty: false)",
     "select": [
      [
       { "params": [ "transferredData" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "veeamjobname", "operator": "=~", "value": "/^$job$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Objects Processed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_jobs",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_office365_jobs\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"processedObjects\")\r\n  |> filter(fn: (r) => r[\"veeamjobname\"] =~ /${job:regex}/)\r\n  |> group(columns: [\"processedObjects\",\"_field\"])\r\n  |> aggregateWindow(every: ${inter}, fn: sum, createEmpty: false)",
     "select": [
      [
       { "params": [ "processedObjects" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "veeamjobname", "operator": "=~", "value": "/^$job$/" }
     ]
    }
   ]
  },
  {
   "title": "Restore Portal Status",
   "type": "stat",
   "description": "Veeam Backup for Microsoft 365 provides users with the ability to explore and restore data from backups by themselves or delegate this task to restore operators.\n",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "veeam_office365_proxies",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_office365_restoreportal\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"restorePortalEnabled\")\r\n  |> aggregateWindow(every: ${inter}, fn: last, createEmpty: false)",
     "select": [
      [
       { "params": [ "threadsNumber" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "proxies", "operator": "=~", "value": "/^$proxies$/" }
     ]
    }
   ]
  },
  {
   "title": "Self-Service Portal, and Restore Operators Security",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Restore Operators",
   "type": "table",
   "description": "In the operator restore scenario, Veeam Backup for Microsoft 365 administrators must add restore operator roles. Inside the Roles, we have the Restore Operators, this is a list with all the Restore Operators, use the variable on the top to change between the different Roles.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_veeamjobname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "veeamjobname" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_jobs",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_office365_rbac_operators\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"rbacRoleAdminId\")\r\n  |> filter(fn: (r) => r[\"organization\"] =~ /${organization:regex}/)\r\n  |> filter(fn: (r) => r[\"rbacRoleName\"] =~ /${rbacrole:regex}/)\r\n  |> group(columns: [\"rbacRoleName\",\"rbacROName\",\"rbacRO365Name\"])\r\n  |> last()",
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "veeamjobname", "operator": "=~", "value": "/^$job$/" }
     ]
    }
   ]
  },
  {
   "title": "Restore Operator Scope",
   "type": "table",
   "description": "Restore operators will be able to explore and restore backed-up data of the objects listed on this table using Restore Portal.",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_veeamjobname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "veeamjobname" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_jobs",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_office365_rbac_scope\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"rbacRoleScopeId\")\r\n  |> filter(fn: (r) => r[\"organization\"] =~ /${organization:regex}/)\r\n  |> filter(fn: (r) => r[\"rbacRoleName\"] =~ /${rbacrole:regex}/)\r\n  |> group(columns: [\"rbacRoleScopeName\",\"rbacRoleName\",\"rbacRoleScope365Name\"])\r\n  |> last()",
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "veeamjobname", "operator": "=~", "value": "/^$job$/" }
     ]
    }
   ]
  },
  {
   "title": "Summaries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$job - Last Result",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 14 },
   "repeat": "job",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "veeamjobname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_jobs",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_office365_jobs\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"status\")\r\n  |> filter(fn: (r) => r[\"veeamjobname\"] =~ /${job:regex}/)\r\n  |> group(columns: [\"status\",\"_field\"])\r\n  |> aggregateWindow(every: ${inter}, fn: last, createEmpty: false)",
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "veeamjobname", "operator": "=~", "value": "/^$job$/" }
     ]
    }
   ]
  },
  {
   "title": "Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Job Read/Write Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "$tag_veeamjobname - read",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "veeamjobname" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_jobs",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_office365_jobs\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"readRate\")\r\n  |> filter(fn: (r) => r[\"veeamjobname\"] =~ /${job:regex}/)\r\n  |> group(columns: [\"readRate\",\"_field\"])\r\n  |> aggregateWindow(every: ${inter}, fn: last, createEmpty: false)",
     "select": [
      [
       { "params": [ "readRate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "veeamjobname", "operator": "=~", "value": "/^$job$/" }
     ]
    },
    {
     "alias": "$tag_veeamjobname - write",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "veeamjobname" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_jobs",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_office365_jobs\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"writeRate\")\r\n  |> filter(fn: (r) => r[\"veeamjobname\"] =~ /${job:regex}/)\r\n  |> group(columns: [\"writeRate\",\"_field\"])\r\n  |> aggregateWindow(every: ${inter}, fn: last, createEmpty: false)",
     "select": [
      [
       { "params": [ "writeRate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "veeamjobname", "operator": "=~", "value": "/^$job$/" }
     ]
    }
   ]
  },
  {
   "title": "Job Processing Rate/Transferred Data",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "alias": "$tag_veeamjobname - processed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "veeamjobname" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_jobs",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_office365_jobs\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"processingRate\")\r\n  |> filter(fn: (r) => r[\"veeamjobname\"] =~ /${job:regex}/)\r\n  |> group(columns: [\"processingRate\",\"_field\"])\r\n  |> aggregateWindow(every: ${inter}, fn: last, createEmpty: false)",
     "select": [
      [
       { "params": [ "processingRate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "veeamjobname", "operator": "=~", "value": "/^$job$/" }
     ]
    },
    {
     "alias": "$tag_veeamjobname - transferred",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "veeamjobname" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_jobs",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_office365_jobs\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"transferredData\")\r\n  |> filter(fn: (r) => r[\"veeamjobname\"] =~ /${job:regex}/)\r\n  |> group(columns: [\"transferredData\",\"_field\"])\r\n  |> aggregateWindow(every: ${inter}, fn: last, createEmpty: false)",
     "select": [
      [
       { "params": [ "transferredData" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "veeamjobname", "operator": "=~", "value": "/^$job$/" }
     ]
    }
   ]
  },
  {
   "title": "Job Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "$tag_veeamjobname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "veeamjobname" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_jobs",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_office365_jobs\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"totalDuration\")\r\n  |> filter(fn: (r) => r[\"veeamjobname\"] =~ /${job:regex}/)\r\n  |> group(columns: [\"veeamjobname\",\"_field\"])\r\n  |> aggregateWindow(every: ${inter}, fn: last, createEmpty: false)",
     "select": [
      [
       { "params": [ "totalDuration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "veeamjobname", "operator": "=~", "value": "/^$job$/" }
     ]
    }
   ]
  },
  {
   "title": "Job Historical Information",
   "type": "table",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_veeamjobname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "veeamjobname" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_jobs",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_office365_jobs\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"status\")\r\n  |> filter(fn: (r) => r[\"veeamjobname\"] =~ /${job:regex}/)\r\n  |> group(columns: [\"veeamjobname\"])\r\n  |> last()",
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "veeamjobname", "operator": "=~", "value": "/^$job$/" }
     ]
    }
   ]
  },
  {
   "title": "Datastores - Usage Capacity",
   "type": "bargauge",
   "description": "This Panel includes the Backup Repositories.\nWhen using Object Storage, it will appear on the right column with the prefix called OBJECT.",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_office365_repository\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"capacity\" or r[\"_field\"] == \"freeSpace\")\r\n  |> filter(fn: (r) => r[\"repository\"] =~ /${repository:regex}/)\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({ r with  _value: (float(v: r.capacity) - float(v: r.freeSpace))  }))\r\n  |> group(columns: [\"repository\",\"_field\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    },
    {
     "alias": "OBJECT - $tag_objectname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_office365_objectstorage\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usedSpaceGB\")\r\n  |> filter(fn: (r) => r[\"objectname\"] =~ /${objectstorage:regex}/)\r\n  |> group(columns: [\"objectname\",\"_field\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Object Storage Status $objectstorage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "repeat": "objectstorage",
   "targets": [
    {}
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "$tag_objectname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "bucketname" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_objectstorage",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_office365_objectstorage\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usedSpaceGB\")\r\n  |> filter(fn: (r) => r[\"objectname\"] =~ /${objectstorage:regex}/)\r\n  |> group(columns: [\"objectname\",\"_field\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)",
     "select": [
      [
       { "params": [ "usedSpaceGB" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "bucketname", "operator": "=~", "value": "/^$objectstorage$/" }
     ]
    }
   ]
  },
  {
   "title": "Used Capacity in Object Storage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 14, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_objectstorage",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_office365_objectstorage\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usedSpaceGB\")\r\n  |> filter(fn: (r) => r[\"objectname\"] =~ /${objectstorage:regex}/)\r\n  |> group(columns: [\"objectname\",\"_field\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)",
     "select": [
      [
       { "params": [ "usedSpaceGB" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "objectname", "operator": "=~", "value": "/^$objectstorage$/" }
     ]
    }
   ]
  },
  {
   "title": "Service Point URL",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_servicePoint",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "servicePoint" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_objectstorage",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_office365_objectstorage\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usedSpaceGB\")\r\n  |> filter(fn: (r) => r[\"objectname\"] =~ /${objectstorage:regex}/)\r\n  |> group(columns: [\"servicePoint\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)",
     "select": [
      [
       { "params": [ "usedSpaceGB" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "objectname", "operator": "=~", "value": "/^$objectstorage$/" }
     ]
    }
   ]
  },
  {
   "title": "Object Storage Type",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 18, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_objectstorage",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_office365_objectstorage\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usedSpaceGB\")\r\n  |> filter(fn: (r) => r[\"objectname\"] =~ /${objectstorage:regex}/)\r\n  |> group(columns: [\"type\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)",
     "select": [
      [
       { "params": [ "usedSpaceGB" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "objectname", "operator": "=~", "value": "/^$objectstorage$/" }
     ]
    }
   ]
  },
  {
   "title": "Region",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_region",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "region" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_objectstorage",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_office365_objectstorage\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usedSpaceGB\")\r\n  |> filter(fn: (r) => r[\"objectname\"] =~ /${objectstorage:regex}/)\r\n  |> group(columns: [\"customRegionId\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)",
     "select": [
      [
       { "params": [ "usedSpaceGB" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "objectname", "operator": "=~", "value": "/^$objectstorage$/" }
     ]
    }
   ]
  },
  {
   "title": "Object Storage Bucket Name",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 18, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_bucketname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "bucketname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_objectstorage",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_office365_objectstorage\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usedSpaceGB\")\r\n  |> filter(fn: (r) => r[\"objectname\"] =~ /${objectstorage:regex}/)\r\n  |> group(columns: [\"bucketname\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)",
     "select": [
      [
       { "params": [ "usedSpaceGB" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "objectname", "operator": "=~", "value": "/^$objectstorage$/" }
     ]
    }
   ]
  },
  {
   "title": "Encryption",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_objectStorageEncryptionEnabled",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "objectStorageEncryptionEnabled" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_objectstorage",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_office365_objectstorage\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usedSpaceGB\")\r\n  |> filter(fn: (r) => r[\"objectname\"] =~ /${objectstorage:regex}/)\r\n  |> group(columns: [\"objectStorageEncryptionEnabled\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)",
     "select": [
      [
       { "params": [ "usedSpaceGB" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "objectname", "operator": "=~", "value": "/^$objectstorage$/" }
     ]
    }
   ]
  },
  {
   "title": "Backup Repositories Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$repository",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 41 },
   "repeat": "repository",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_repository",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_office365_repository\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"capacity\" or r[\"_field\"] == \"freeSpace\")\r\n  |> filter(fn: (r) => r[\"repository\"] =~ /${repository:regex}/)\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({ r with  _value: (float(v: r.capacity) - float(v: r.freeSpace)) * (100.0 /float(v: r.capacity)) }))\r\n  |> group(columns: [\"repository\",\"_field\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)",
     "select": [
      [
       { "params": [ "capacity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "repository", "operator": "=~", "value": "/^$repository$/" }
     ]
    }
   ]
  }
 ]
}