{
 "title": "Grafana Dashboard for Veeam Backup for Microsoft Office 365 v4",
 "description": "Grafana Dashboard for Veeam Backup for Microsoft Office 365 Dashboard - Works only with v4.0 of VBO",
 "tags": [
  "Veeam",
  "Office 365"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "inter",
    "label": "Sampling",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "organization",
    "label": "Organization",
    "query": "SHOW TAG VALUES FROM veeam_office365_organization WITH KEY=veeamOrgName"
   },
   {
    "name": "job",
    "label": "Backup Job",
    "query": "SHOW TAG VALUES FROM veeam_office365_jobs WITH KEY=veeamjobname"
   },
   {
    "name": "proxies",
    "label": "Backup Proxies",
    "query": "SHOW TAG VALUES FROM veeam_office365_proxies WITH KEY=proxies"
   },
   {
    "name": "repository",
    "label": "Backup Repository",
    "query": "SHOW TAG VALUES FROM veeam_office365_repository WITH KEY=repository"
   },
   {
    "name": "objectstorage",
    "label": "Object Storage",
    "query": "SHOW TAG VALUES FROM veeam_office365_objectstorage WITH KEY=objectname"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "content": "![Veeam Backup for Microsoft Office 365 - Dashboard](https://www.jorgedelacruz.es/wp-content/uploads/2020/05/Ofc365_rgb_Orng166.png)"
  },
  {
   "title": "Licensed Users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_organization",
     "query": "SELECT last(\"uptime_latest\") FROM \"vsphere_host_sys\" WHERE (\"esxhostname\" =~ /^$esxi$/ AND \"vcenter\" =~ /^$vcenter$/ AND \"clustername\" =~ /^$clustername$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "licensedUsers" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "veeamOrgName", "operator": "=~", "value": "/^$organization$/" }
     ]
    }
   ]
  },
  {
   "title": "New Users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_organization",
     "query": "SELECT last(\"uptime_latest\") FROM \"vsphere_host_sys\" WHERE (\"esxhostname\" =~ /^$esxi$/ AND \"vcenter\" =~ /^$vcenter$/ AND \"clustername\" =~ /^$clustername$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "newUsers" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "veeamOrgName", "operator": "=~", "value": "/^$organization$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Threads Numbers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "veeam_office365_proxies",
     "query": "SELECT sum(\"threadsNumber\") FROM \"veeam_office365_proxies\" WHERE (\"proxies\" =~ /^$proxies$/) AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "threadsNumber" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "proxies", "operator": "=~", "value": "/^$proxies$/" }
     ]
    }
   ]
  },
  {
   "title": "Change Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "veeam_office365_jobs",
     "query": "SELECT last(\"uptime_latest\") FROM \"vsphere_host_sys\" WHERE (\"esxhostname\" =~ /^$esxi$/ AND \"vcenter\" =~ /^$vcenter$/ AND \"clustername\" =~ /^$clustername$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "transferredData" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "veeamjobname", "operator": "=~", "value": "/^$job$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Objects Processed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_jobs",
     "query": "SELECT last(\"uptime_latest\") FROM \"vsphere_host_sys\" WHERE (\"esxhostname\" =~ /^$esxi$/ AND \"vcenter\" =~ /^$vcenter$/ AND \"clustername\" =~ /^$clustername$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "processedObjects" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "veeamjobname", "operator": "=~", "value": "/^$job$/" }
     ]
    }
   ]
  },
  { "title": "Summaries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "$job - Last Result",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4.8, "x": 0, "y": 6 },
   "repeat": "job",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "veeamjobname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_jobs",
     "query": "SELECT last(\"uptime_latest\") FROM \"vsphere_host_sys\" WHERE (\"esxhostname\" =~ /^$esxi$/ AND \"vcenter\" =~ /^$vcenter$/ AND \"clustername\" =~ /^$clustername$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "veeamjobname", "operator": "=~", "value": "/^$job$/" }
     ]
    }
   ]
  },
  {
   "title": "$job - Restore - Items Processed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4.8, "x": 0, "y": 9 },
   "repeat": "job",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "veeamjobname" ], "type": "tag" }
     ],
     "measurement": "veeam_office365_restoresession",
     "query": "SELECT last(\"uptime_latest\") FROM \"vsphere_host_sys\" WHERE (\"esxhostname\" =~ /^$esxi$/ AND \"vcenter\" =~ /^$vcenter$/ AND \"clustername\" =~ /^$clustername$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "itemsProcessed" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "veeamjobname", "operator": "=~", "value": "/^$job$/" }
     ]
    }
   ]
  },
  {
   "title": "$job - Restore - Items Recovered",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4.8, "x": 0, "y": 12 },
   "repeat": "job",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "veeamjobname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_restoresession",
     "query": "SELECT last(\"uptime_latest\") FROM \"vsphere_host_sys\" WHERE (\"esxhostname\" =~ /^$esxi$/ AND \"vcenter\" =~ /^$vcenter$/ AND \"clustername\" =~ /^$clustername$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "itemsSuccess" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "veeamjobname", "operator": "=~", "value": "/^$job$/" }
     ]
    }
   ]
  },
  { "title": "Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Job Read/Write Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "Bps", "label": "Read MB/s" }
   ],
   "targets": [
    {
     "alias": "$tag_veeamjobname - read",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "veeamjobname" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_jobs",
     "query": "SELECT mean(\"usage_average\") FROM \"vsphere_host_cpu\" WHERE \"esxhostname\" = ($esxi) AND $timeFilter GROUP BY time($__interval), \"host\" fill(none)",
     "select": [
      [
       { "params": [ "readRate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "veeamjobname", "operator": "=~", "value": "/^$job$/" }
     ]
    },
    {
     "alias": "$tag_veeamjobname - write",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "veeamjobname" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_jobs",
     "query": "SELECT mean(\"usage_average\") FROM \"vsphere_host_cpu\" WHERE \"esxhostname\" = ($esxi) AND $timeFilter GROUP BY time($__interval), \"host\" fill(none)",
     "select": [
      [
       { "params": [ "writeRate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "veeamjobname", "operator": "=~", "value": "/^$job$/" }
     ]
    }
   ]
  },
  {
   "title": "Job Processing Rate/Transferred Data",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "KBs", "label": "Processed KB/s" }
   ],
   "targets": [
    {
     "alias": "$tag_veeamjobname - processed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "veeamjobname" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_jobs",
     "query": "SELECT mean(\"usage_average\") FROM \"vsphere_host_cpu\" WHERE \"esxhostname\" = ($esxi) AND $timeFilter GROUP BY time($__interval), \"host\" fill(none)",
     "select": [
      [
       { "params": [ "processingRate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "veeamjobname", "operator": "=~", "value": "/^$job$/" }
     ]
    },
    {
     "alias": "$tag_veeamjobname - transferred",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "veeamjobname" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_jobs",
     "query": "SELECT mean(\"usage_average\") FROM \"vsphere_host_cpu\" WHERE \"esxhostname\" = ($esxi) AND $timeFilter GROUP BY time($__interval), \"host\" fill(none)",
     "select": [
      [
       { "params": [ "transferredData" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "veeamjobname", "operator": "=~", "value": "/^$job$/" }
     ]
    }
   ]
  },
  {
   "title": "Job Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "s", "label": "Duration in Seconds" }
   ],
   "targets": [
    {
     "alias": "$tag_veeamjobname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "veeamjobname" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_jobs",
     "query": "SELECT mean(\"usage_average\") FROM \"vsphere_host_cpu\" WHERE \"esxhostname\" = ($esxi) AND $timeFilter GROUP BY time($__interval), \"host\" fill(none)",
     "select": [
      [
       { "params": [ "totalDuration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "veeamjobname", "operator": "=~", "value": "/^$job$/" }
     ]
    }
   ]
  },
  {
   "title": "Job Historical Information",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 23 },
   "targets": [
    {
     "alias": "$tag_veeamjobname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "veeamjobname" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_jobs",
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "veeamjobname", "operator": "=~", "value": "/^$job$/" }
     ]
    }
   ]
  },
  {
   "title": "Datastores - Usage Capacity",
   "type": "graph",
   "description": "This Panel includes the Backup Repositories.\nWhen using Object Storage, it will appear on the right column with the prefix called OBJECT.",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 23 },
   "yaxes": [
    { "format": "decbytes", "label": "Used Space GB" }
   ],
   "targets": [
    {
     "alias": "CACHE - $tag_repository",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "source" ], "type": "tag" }
     ],
     "measurement": "vsphere_datastore_disk",
     "query": "SELECT  (mean(\"capacity\") - mean(\"freeSpace\"))  FROM  \"veeam_office365_repository\" WHERE (\"repository\" =~ /^$repository$/) AND $timeFilter GROUP BY time(5m), \"repository\"",
     "select": [
      [
       { "params": [ "capacity_latest" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$datastore$/" }
     ]
    },
    {
     "alias": "OBJECT - $tag_objectname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"usedSpaceGB\") FROM \"veeam_office365_objectstorage\" WHERE (\"objectname\" =~ /^$objectstorage$/) AND $timeFilter GROUP BY time($__interval), \"objectname\" fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Object Storage Status $objectstorage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "repeat": "objectstorage"
  },
  {
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 32 },
   "yaxes": [
    {
     "format": "decbytes",
     "label": "Consumed Space in Object Storage"
    }
   ],
   "targets": [
    {
     "alias": "$tag_objectname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "bucketname" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_objectstorage",
     "query": "SELECT last(\"usedSpaceGB\") FROM \"veeam_office365_objectstorage\" WHERE (\"objectname\" =~ /^$objectstorage$/) AND $timeFilter GROUP BY time($__interval), \"objectname\" fill(none)",
     "select": [
      [
       { "params": [ "usedSpaceGB" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "bucketname", "operator": "=~", "value": "/^$objectstorage$/" }
     ]
    }
   ]
  },
  {
   "title": "Used Capacity in Object Storage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 14, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_objectstorage",
     "select": [
      [
       { "params": [ "usedSpaceGB" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "objectname", "operator": "=~", "value": "/^$objectstorage$/" }
     ]
    }
   ]
  },
  {
   "title": "Service Point URL",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 32 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "alias": "$tag_servicePoint",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "servicePoint" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_objectstorage",
     "select": [
      [
       { "params": [ "usedSpaceGB" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "objectname", "operator": "=~", "value": "/^$objectstorage$/" }
     ]
    }
   ]
  },
  {
   "title": "Object Storage Type",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 18, "y": 34 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "alias": "$tag_type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_objectstorage",
     "select": [
      [
       { "params": [ "usedSpaceGB" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "objectname", "operator": "=~", "value": "/^$objectstorage$/" }
     ]
    }
   ]
  },
  {
   "title": "Region",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 34 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "alias": "$tag_region",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "region" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_objectstorage",
     "select": [
      [
       { "params": [ "usedSpaceGB" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "objectname", "operator": "=~", "value": "/^$objectstorage$/" }
     ]
    }
   ]
  },
  {
   "title": "Object Storage Bucket Name",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 18, "y": 36 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "alias": "$tag_bucketname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "bucketname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_objectstorage",
     "select": [
      [
       { "params": [ "usedSpaceGB" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "objectname", "operator": "=~", "value": "/^$objectstorage$/" }
     ]
    }
   ]
  },
  {
   "title": "Encryption",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 36 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "alias": "$tag_objectStorageEncryptionEnabled",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "objectStorageEncryptionEnabled" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_objectstorage",
     "select": [
      [
       { "params": [ "usedSpaceGB" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "objectname", "operator": "=~", "value": "/^$objectstorage$/" }
     ]
    }
   ]
  },
  { "title": "Backup Repositories Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "$repository",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 39 },
   "repeat": "repository",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_repository",
     "query": "SELECT  (mean(\"capacity\") - mean(\"freeSpace\")) * (100 / mean(\"capacity\"))  FROM  \"veeam_office365_repository\" WHERE (\"repository\" =~ /^$repository$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "capacity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "repository", "operator": "=~", "value": "/^$repository$/" }
     ]
    }
   ]
  }
 ]
}