{
 "title": "Grafana Dashboard for User Audit VB365",
 "description": "Grafana Dashboard for User Audit for Restore Portal of Veeam Backup for Microsoft 365",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "RestorePortalID",
    "label": "Restore Portal ID",
    "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_microsoft365_audit\")\r\n  |> keep(columns: [\"veeamVBMRPAppID\"])\r\n  |> distinct(column: \"veeamVBMRPAppID\")\r\n  |> group()\r\n"
   },
   {
    "name": "RestorePortalUser",
    "label": "Restore Portal User",
    "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_microsoft365_audit\")\r\n  |> keep(columns: [\"veeamVBMRPUserPN\"])\r\n  |> distinct(column: \"veeamVBMRPUserPN\")\r\n  |> group()\r\n"
   },
   {
    "name": "RestorePortalUserDevice",
    "label": "Restore Portal User Device",
    "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_microsoft365_audit\")\r\n  |> keep(columns: [\"veeamVBMRPLoginDevice\"])\r\n  |> distinct(column: \"veeamVBMRPLoginDevice\")\r\n  |> group()\r\n"
   },
   {
    "name": "RestorePortalUserBrowser",
    "label": "Restore Portal User Browser",
    "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_microsoft365_audit\")\r\n  |> keep(columns: [\"veeamVBMRPLoginBrowser\"])\r\n  |> distinct(column: \"veeamVBMRPLoginBrowser\")\r\n  |> group()\r\n"
   }
  ]
 },
 "panels": [
  {
   "title": "Veeam Restore Portal - Activity Details Audit World Map",
   "type": "geomap",
   "description": "On this Map, you can quickly know which End-Users, Tenants, or Restore Operators have logged in into the Restore Portal, from where, IP Address, Web Browser, and Operating System.",
   "gridPos": { "h": 15, "w": 18, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_microsoft365_audit\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"veeamVBMRPLoginLocationCityGEOLAT\" or r[\"_field\"] == \"veeamVBMRPLoginLocationCityGEOLONG\")\r\n  |> filter(fn: (r) => r[\"veeamVBMRPAppID\"] =~ /${RestorePortalID:regex}/)\r\n  |> filter(fn: (r) => r[\"veeamVBMRPLoginDevice\"] =~ /${RestorePortalUserDevice:regex}/)\r\n  |> filter(fn: (r) => r[\"veeamVBMRPLoginBrowser\"] =~ /${RestorePortalUserBrowser:regex}/)\r\n    |> filter(fn: (r) => r[\"veeamVBMRPUserPN\"] =~ /${RestorePortalUser:regex}/)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_microsoft365_audit\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"veeamVBMRPLoginLocationCityGEOLAT\")\r\n  |> filter(fn: (r) => r[\"veeamVBMRPAppID\"] =~ /${RestorePortalID:regex}/)\r\n  |> group(columns: [\"veeamVBMRPUserDN\"])\r\n  |> count()\r\n  |> yield(name: \"count\")"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_microsoft365_audit\")\r\n  |> keep(columns: [\"veeamVBMRPLoginID\"])\r\n  |> distinct(column: \"veeamVBMRPLoginID\")\r\n  |> group()\r\n  |> count()"
    },
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_microsoft365_audit\")\r\n  |> keep(columns: [\"veeamVBMRPUserDN\"])\r\n  |> distinct(column: \"veeamVBMRPUserDN\")\r\n  |> group()\r\n  |> count()"
    }
   ]
  },
  {
   "title": "Logins by Web Browser",
   "type": "piechart",
   "description": "Pie Chart with the most common used Web Browsers to login to the Veeam Restore Portal.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_microsoft365_audit\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"veeamVBMRPLoginLocationCityGEOLAT\")\r\n  |> filter(fn: (r) => r[\"veeamVBMRPAppID\"] =~ /${RestorePortalID:regex}/)\r\n  |> group(columns: [\"veeamVBMRPLoginBrowser\"])\r\n  |> count()\r\n  |> yield(name: \"count\")"
    }
   ]
  },
  {
   "title": "Logins by Operating System",
   "type": "piechart",
   "description": "Pie Chart with the most common used Operating Systems to login to the Veeam Restore Portal.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_microsoft365_audit\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"veeamVBMRPLoginLocationCityGEOLAT\")\r\n  |> filter(fn: (r) => r[\"veeamVBMRPAppID\"] =~ /${RestorePortalID:regex}/)\r\n  |> group(columns: [\"veeamVBMRPLoginDevice\"])\r\n  |> count()\r\n  |> yield(name: \"count\")"
    }
   ]
  },
  {
   "title": "Activity Details",
   "type": "table",
   "description": "Please find all the Sign-in to the Veeam Restore Portal that you have selected from the drop-down menus. You can filter as well per ",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_microsoft365_audit\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"veeamVBMRPLoginLocationCityGEOLAT\")\r\n  |> filter(fn: (r) => r[\"veeamVBMRPAppID\"] =~ /${RestorePortalID:regex}/)\r\n  |> filter(fn: (r) => r[\"veeamVBMRPLoginDevice\"] =~ /${RestorePortalUserDevice:regex}/)\r\n  |> filter(fn: (r) => r[\"veeamVBMRPLoginBrowser\"] =~ /${RestorePortalUserBrowser:regex}/)\r\n    |> filter(fn: (r) => r[\"veeamVBMRPUserPN\"] =~ /${RestorePortalUser:regex}/)\r\n  |> group(columns: [\"veeamVBMRPLoginID\"])\r\n  |> last()"
    }
   ]
  }
 ]
}