{
 "title": "Grafana Dashboard for Veeam Backup for Microsoft 365 Audit Restores",
 "description": "Grafana Dashboard for Veeam Backup for Microsoft 365 Audit Restores",
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "VB365Org",
    "label": "Microsoft Organization",
    "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_m365_auditrestore\")\r\n  |> keep(columns: [\"vb365_organization\"])\r\n  |> distinct(column: \"vb365_organization\")\r\n  |> group()"
   },
   {
    "name": "VB365Type",
    "label": "Restore Type",
    "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_m365_auditrestore\")\r\n  |> keep(columns: [\"vb365_restoresession_type\"])\r\n  |> distinct(column: \"vb365_restoresession_type\")\r\n  |> group()"
   },
   {
    "name": "VB365Initiated",
    "label": "Restore Admin",
    "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_m365_auditrestore\")\r\n  |> keep(columns: [\"vb365_restoresession_initiatedby\"])\r\n  |> distinct(column: \"vb365_restoresession_initiatedby\")\r\n  |> group()"
   },
   {
    "name": "VB365AdminIP",
    "label": "Restore Session IP",
    "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_m365_auditrestore\")\r\n  |> keep(columns: [\"vb365_restoresession_clienthost\"])\r\n  |> distinct(column: \"vb365_restoresession_clienthost\")\r\n  |> group()"
   },
   {
    "name": "VB365EventType",
    "label": "Restore Event Type",
    "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_m365_auditrestore_event\")\r\n  |> keep(columns: [\"vb365_restoresession_event_type\"])\r\n  |> distinct(column: \"vb365_restoresession_event_type\")\r\n  |> group()"
   }
  ]
 },
 "panels": [
  {
   "title": "Restore Operations per Administrator",
   "type": "piechart",
   "description": "Pie chart with a detailed number of Restore Operations per Restore Operator, or Restore Administrator",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_m365_auditrestore\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"vb365_restoresession_result\")\r\n  |> filter(fn: (r) => r[\"vb365_restoresession_initiatedby\"] =~ /${VB365Initiated:regex}/)\r\n  |> group(columns: [\"vb365_restoresession_initiatedby\"])\r\n  |> count()\r\n  |> yield(name: \"count\")"
    }
   ]
  },
  {
   "title": "Restore Operations per Microsoft Service",
   "type": "timeseries",
   "description": "The last 7 days restores per Microsoft 365 Service. For example, Exchange Online, SharePoint, etc.",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_m365_auditrestore\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"vb365_restoresession_result\")\r\n  |> group(columns: [\"vb365_restoresession_type\"])\r\n    |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")\r\n"
    }
   ]
  },
  {
   "title": "Restore Operations Audit",
   "type": "table",
   "description": "Table with high-level details of every Restore Operation Session, and includes Initiated By, IP, Scope, etc.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_m365_auditrestore\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"vb365_restoresession_result\")\r\n  |> filter(fn: (r) => r[\"vb365_organization\"] =~ /${VB365Org:regex}/)\r\n  |> filter(fn: (r) => r[\"vb365_restoresession_type\"] =~ /${VB365Type:regex}/)\r\n  |> filter(fn: (r) => r[\"vb365_restoresession_initiatedby\"] =~ /${VB365Initiated:regex}/)\r\n  |> filter(fn: (r) => r[\"vb365_restoresession_clienthost\"] =~ /${VB365AdminIP:regex}/)\r\n  |> group(columns: [\"vb365_restoresession_id\"])\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Restore Operations Audit - Extended level",
   "type": "logs",
   "description": "Log view with low-level details of every Restore Operation Session, and includes Initiated By, IP, Scope, etc.",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_m365_auditrestore_event\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"vb365_restoresession_event_SizeBytes\")\r\n  |> filter(fn: (r) => r[\"vb365_organization\"] =~ /${VB365Org:regex}/)\r\n  |> filter(fn: (r) => r[\"vb365_restoresession_type\"] =~ /${VB365Type:regex}/)\r\n  |> filter(fn: (r) => r[\"vb365_restoresession_initiatedby\"] =~ /${VB365Initiated:regex}/)\r\n  |> filter(fn: (r) => r[\"vb365_restoresession_clienthost\"] =~ /${VB365AdminIP:regex}/)\r\n  |> filter(fn: (r) => r[\"vb365_restoresession_event_type\"] =~ /${VB365EventType:regex}/)\r\n  |> last()"
    }
   ]
  }
 ]
}