{
 "title": "Grafana Dashboard for Veeam Backup for Microsoft 365",
 "description": "Grafana Dashboard for Veeam Backup for Microsoft 365 Dashboard / VBO v5 + Influx v2",
 "tags": [
  "Veeam",
  "Office 365"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "inter",
    "label": "Sampling",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "organization",
    "label": "Organization",
    "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_office365_organization\")\r\n  |> keep(columns: [\"veeamOrgName\"])\r\n  |> distinct(column: \"veeamOrgName\")\r\n  |> group()"
   },
   {
    "name": "job",
    "label": "Backup Job",
    "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_office365_jobs\")\r\n  |> keep(columns: [\"veeamjobname\"])\r\n  |> distinct(column: \"veeamjobname\")\r\n  |> group()"
   },
   {
    "name": "proxies",
    "label": "Backup Proxies",
    "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_office365_proxies\")\r\n  |> keep(columns: [\"proxies\"])\r\n  |> distinct(column: \"proxies\")\r\n  |> group()"
   },
   {
    "name": "repository",
    "label": "Backup Repository",
    "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_office365_repository\")\r\n  |> keep(columns: [\"repository\"])\r\n  |> distinct(column: \"repository\")\r\n  |> group()"
   },
   {
    "name": "objectstorage",
    "label": "Object Storage",
    "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_office365_objectstorage\")\r\n  |> keep(columns: [\"objectname\"])\r\n  |> distinct(column: \"objectname\")\r\n  |> group()\r\n"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "options": {
    "content": "![Veeam Backup for Microsoft 365 - Dashboard](https://jorgedelacruz.uk/wp-content/uploads/2022/03/Microsoft-Office-365-Logo3.png)"
   }
  },
  {
   "title": "Licensed Users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_organization",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_office365_organization\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"licensedUsers\")\r\n  |> filter(fn: (r) => r[\"veeamOrgName\"] =~ /${organization:regex}/)\r\n  |> group(columns: [\"licensedUsers\",\"_field\"])\r\n  |> aggregateWindow(every: ${inter}, fn: sum, createEmpty: false)",
     "select": [
      [
       { "params": [ "licensedUsers" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "veeamOrgName", "operator": "=~", "value": "/^$organization$/" }
     ]
    }
   ]
  },
  {
   "title": "New Users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_organization",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_office365_organization\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"newUsers\")\r\n  |> filter(fn: (r) => r[\"veeamOrgName\"] =~ /${organization:regex}/)\r\n  |> group(columns: [\"newUsers\",\"_field\"])\r\n  |> aggregateWindow(every: ${inter}, fn: sum, createEmpty: false)",
     "select": [
      [
       { "params": [ "newUsers" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "veeamOrgName", "operator": "=~", "value": "/^$organization$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Threads Numbers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "veeam_office365_proxies",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_office365_proxies\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"threadsNumber\")\r\n  |> filter(fn: (r) => r[\"proxies\"] =~ /${proxies:regex}/)\r\n  |> group(columns: [\"threadsNumber\",\"_field\"])\r\n  |> aggregateWindow(every: ${inter}, fn: last, createEmpty: false)",
     "select": [
      [
       { "params": [ "threadsNumber" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "proxies", "operator": "=~", "value": "/^$proxies$/" }
     ]
    }
   ]
  },
  {
   "title": "Change Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "veeam_office365_jobs",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_office365_jobs\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"transferredData\")\r\n  |> filter(fn: (r) => r[\"veeamjobname\"] =~ /${job:regex}/)\r\n  |> group(columns: [\"transferredData\",\"_field\"])\r\n  |> aggregateWindow(every: ${inter}, fn: sum, createEmpty: false)",
     "select": [
      [
       { "params": [ "transferredData" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "veeamjobname", "operator": "=~", "value": "/^$job$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Objects Processed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_jobs",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_office365_jobs\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"processedObjects\")\r\n  |> filter(fn: (r) => r[\"veeamjobname\"] =~ /${job:regex}/)\r\n  |> group(columns: [\"processedObjects\",\"_field\"])\r\n  |> aggregateWindow(every: ${inter}, fn: sum, createEmpty: false)",
     "select": [
      [
       { "params": [ "processedObjects" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "veeamjobname", "operator": "=~", "value": "/^$job$/" }
     ]
    }
   ]
  },
  { "title": "Summaries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "$job - Last Result",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 6 },
   "repeat": "job",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "veeamjobname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_jobs",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_office365_jobs\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"status\")\r\n  |> filter(fn: (r) => r[\"veeamjobname\"] =~ /${job:regex}/)\r\n  |> group(columns: [\"status\",\"_field\"])\r\n  |> aggregateWindow(every: ${inter}, fn: last, createEmpty: false)",
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "veeamjobname", "operator": "=~", "value": "/^$job$/" }
     ]
    }
   ]
  },
  {
   "title": "Restore Operations Tracking",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "$job - Restore - Items Recovered",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 10 },
     "repeat": "job",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "veeamjobname" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "veeam_office365_restoresession",
       "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_office365_jobs\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"itemsSuccess\")\r\n  |> filter(fn: (r) => r[\"veeamjobname\"] =~ /${job:regex}/)\r\n  |> group(columns: [\"itemsSuccess\",\"_field\"])\r\n  |> aggregateWindow(every: ${inter}, fn: last, createEmpty: false)",
       "select": [
        [
         { "params": [ "itemsSuccess" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "veeamjobname", "operator": "=~", "value": "/^$job$/" }
       ]
      }
     ]
    },
    {
     "title": "$job - Restore - Items Processed",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 13 },
     "repeat": "job",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "veeamjobname" ], "type": "tag" }
       ],
       "measurement": "veeam_office365_restoresession",
       "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_office365_jobs\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"itemsProcessed\")\r\n  |> filter(fn: (r) => r[\"veeamjobname\"] =~ /${job:regex}/)\r\n  |> group(columns: [\"itemsProcessed\",\"_field\"])\r\n  |> aggregateWindow(every: ${inter}, fn: last, createEmpty: false)",
       "select": [
        [
         { "params": [ "itemsProcessed" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "veeamjobname", "operator": "=~", "value": "/^$job$/" }
       ]
      }
     ]
    }
   ]
  },
  { "title": "Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Job Read/Write Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "$tag_veeamjobname - read",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "veeamjobname" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_jobs",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_office365_jobs\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"readRate\")\r\n  |> filter(fn: (r) => r[\"veeamjobname\"] =~ /${job:regex}/)\r\n  |> group(columns: [\"readRate\",\"_field\"])\r\n  |> aggregateWindow(every: ${inter}, fn: last, createEmpty: false)",
     "select": [
      [
       { "params": [ "readRate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "veeamjobname", "operator": "=~", "value": "/^$job$/" }
     ]
    },
    {
     "alias": "$tag_veeamjobname - write",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "veeamjobname" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_jobs",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_office365_jobs\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"writeRate\")\r\n  |> filter(fn: (r) => r[\"veeamjobname\"] =~ /${job:regex}/)\r\n  |> group(columns: [\"writeRate\",\"_field\"])\r\n  |> aggregateWindow(every: ${inter}, fn: last, createEmpty: false)",
     "select": [
      [
       { "params": [ "writeRate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "veeamjobname", "operator": "=~", "value": "/^$job$/" }
     ]
    }
   ]
  },
  {
   "title": "Job Processing Rate/Transferred Data",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "alias": "$tag_veeamjobname - processed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "veeamjobname" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_jobs",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_office365_jobs\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"processingRate\")\r\n  |> filter(fn: (r) => r[\"veeamjobname\"] =~ /${job:regex}/)\r\n  |> group(columns: [\"processingRate\",\"_field\"])\r\n  |> aggregateWindow(every: ${inter}, fn: last, createEmpty: false)",
     "select": [
      [
       { "params": [ "processingRate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "veeamjobname", "operator": "=~", "value": "/^$job$/" }
     ]
    },
    {
     "alias": "$tag_veeamjobname - transferred",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "veeamjobname" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_jobs",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_office365_jobs\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"transferredData\")\r\n  |> filter(fn: (r) => r[\"veeamjobname\"] =~ /${job:regex}/)\r\n  |> group(columns: [\"transferredData\",\"_field\"])\r\n  |> aggregateWindow(every: ${inter}, fn: last, createEmpty: false)",
     "select": [
      [
       { "params": [ "transferredData" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "veeamjobname", "operator": "=~", "value": "/^$job$/" }
     ]
    }
   ]
  },
  {
   "title": "Job Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "$tag_veeamjobname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "veeamjobname" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_jobs",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_office365_jobs\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"totalDuration\")\r\n  |> filter(fn: (r) => r[\"veeamjobname\"] =~ /${job:regex}/)\r\n  |> group(columns: [\"veeamjobname\",\"_field\"])\r\n  |> aggregateWindow(every: ${inter}, fn: last, createEmpty: false)",
     "select": [
      [
       { "params": [ "totalDuration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "veeamjobname", "operator": "=~", "value": "/^$job$/" }
     ]
    }
   ]
  },
  {
   "title": "Job Historical Information",
   "type": "table",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_veeamjobname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "veeamjobname" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_jobs",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_office365_jobs\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"status\")\r\n  |> filter(fn: (r) => r[\"veeamjobname\"] =~ /${job:regex}/)\r\n  |> group(columns: [\"veeamjobname\"])\r\n  |> last()",
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "veeamjobname", "operator": "=~", "value": "/^$job$/" }
     ]
    }
   ]
  },
  {
   "title": "Datastores - Usage Capacity",
   "type": "bargauge",
   "description": "This Panel includes the Backup Repositories.\nWhen using Object Storage, it will appear on the right column with the prefix called OBJECT.",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_office365_repository\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"capacity\" or r[\"_field\"] == \"freeSpace\")\r\n  |> filter(fn: (r) => r[\"repository\"] =~ /${repository:regex}/)\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({ r with  _value: (float(v: r.capacity) - float(v: r.freeSpace))  }))\r\n  |> group(columns: [\"repository\",\"_field\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    },
    {
     "alias": "OBJECT - $tag_objectname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_office365_objectstorage\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usedSpaceGB\")\r\n  |> filter(fn: (r) => r[\"objectname\"] =~ /${objectstorage:regex}/)\r\n  |> group(columns: [\"objectname\",\"_field\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Object Storage Status $objectstorage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "repeat": "objectstorage"
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "$tag_objectname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "bucketname" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_objectstorage",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_office365_objectstorage\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usedSpaceGB\")\r\n  |> filter(fn: (r) => r[\"objectname\"] =~ /${objectstorage:regex}/)\r\n  |> group(columns: [\"objectname\",\"_field\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)",
     "select": [
      [
       { "params": [ "usedSpaceGB" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "bucketname", "operator": "=~", "value": "/^$objectstorage$/" }
     ]
    }
   ]
  },
  {
   "title": "Used Capacity in Object Storage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 14, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_objectstorage",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_office365_objectstorage\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usedSpaceGB\")\r\n  |> filter(fn: (r) => r[\"objectname\"] =~ /${objectstorage:regex}/)\r\n  |> group(columns: [\"objectname\",\"_field\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)",
     "select": [
      [
       { "params": [ "usedSpaceGB" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "objectname", "operator": "=~", "value": "/^$objectstorage$/" }
     ]
    }
   ]
  },
  {
   "title": "Service Point URL",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_servicePoint",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "servicePoint" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_objectstorage",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_office365_objectstorage\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usedSpaceGB\")\r\n  |> filter(fn: (r) => r[\"objectname\"] =~ /${objectstorage:regex}/)\r\n  |> group(columns: [\"servicePoint\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)",
     "select": [
      [
       { "params": [ "usedSpaceGB" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "objectname", "operator": "=~", "value": "/^$objectstorage$/" }
     ]
    }
   ]
  },
  {
   "title": "Object Storage Type",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 18, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_objectstorage",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_office365_objectstorage\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usedSpaceGB\")\r\n  |> filter(fn: (r) => r[\"objectname\"] =~ /${objectstorage:regex}/)\r\n  |> group(columns: [\"type\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)",
     "select": [
      [
       { "params": [ "usedSpaceGB" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "objectname", "operator": "=~", "value": "/^$objectstorage$/" }
     ]
    }
   ]
  },
  {
   "title": "Region",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_region",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "region" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_objectstorage",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_office365_objectstorage\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usedSpaceGB\")\r\n  |> filter(fn: (r) => r[\"objectname\"] =~ /${objectstorage:regex}/)\r\n  |> group(columns: [\"customRegionId\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)",
     "select": [
      [
       { "params": [ "usedSpaceGB" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "objectname", "operator": "=~", "value": "/^$objectstorage$/" }
     ]
    }
   ]
  },
  {
   "title": "Object Storage Bucket Name",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 18, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_bucketname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "bucketname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_objectstorage",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_office365_objectstorage\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usedSpaceGB\")\r\n  |> filter(fn: (r) => r[\"objectname\"] =~ /${objectstorage:regex}/)\r\n  |> group(columns: [\"bucketname\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)",
     "select": [
      [
       { "params": [ "usedSpaceGB" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "objectname", "operator": "=~", "value": "/^$objectstorage$/" }
     ]
    }
   ]
  },
  {
   "title": "Encryption",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_objectStorageEncryptionEnabled",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "objectStorageEncryptionEnabled" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_objectstorage",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_office365_objectstorage\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usedSpaceGB\")\r\n  |> filter(fn: (r) => r[\"objectname\"] =~ /${objectstorage:regex}/)\r\n  |> group(columns: [\"objectStorageEncryptionEnabled\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)",
     "select": [
      [
       { "params": [ "usedSpaceGB" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "objectname", "operator": "=~", "value": "/^$objectstorage$/" }
     ]
    }
   ]
  },
  { "title": "Backup Repositories Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "$repository",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 37 },
   "repeat": "repository",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_repository",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_office365_repository\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"capacity\" or r[\"_field\"] == \"freeSpace\")\r\n  |> filter(fn: (r) => r[\"repository\"] =~ /${repository:regex}/)\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({ r with  _value: (float(v: r.capacity) - float(v: r.freeSpace)) * (100.0 /float(v: r.capacity)) }))\r\n  |> group(columns: [\"repository\",\"_field\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)",
     "select": [
      [
       { "params": [ "capacity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "repository", "operator": "=~", "value": "/^$repository$/" }
     ]
    }
   ]
  }
 ]
}